// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: config/tracing/config.proto

package tracing

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
	meta "zengo/platform/api/config/meta"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OTLP transport protocol.
//
// Protocol selects the OTLP transport protocol.
type Spec_Protocol int32

const (
	Spec_PROTOCOL_UNSPECIFIED Spec_Protocol = 0
	Spec_GRPC                 Spec_Protocol = 1
	Spec_HTTP                 Spec_Protocol = 2
)

// Enum value maps for Spec_Protocol.
var (
	Spec_Protocol_name = map[int32]string{
		0: "PROTOCOL_UNSPECIFIED",
		1: "GRPC",
		2: "HTTP",
	}
	Spec_Protocol_value = map[string]int32{
		"PROTOCOL_UNSPECIFIED": 0,
		"GRPC":                 1,
		"HTTP":                 2,
	}
)

func (x Spec_Protocol) Enum() *Spec_Protocol {
	p := new(Spec_Protocol)
	*p = x
	return p
}

func (x Spec_Protocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Spec_Protocol) Descriptor() protoreflect.EnumDescriptor {
	return file_config_tracing_config_proto_enumTypes[0].Descriptor()
}

func (Spec_Protocol) Type() protoreflect.EnumType {
	return &file_config_tracing_config_proto_enumTypes[0]
}

func (x Spec_Protocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Spec_Protocol.Descriptor instead.
func (Spec_Protocol) EnumDescriptor() ([]byte, []int) {
	return file_config_tracing_config_proto_rawDescGZIP(), []int{1, 0}
}

// Tracing config document.
//
// Config is the typed tracing configuration loaded by the platform runtime.
type Config struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Config kind.
	//
	// kind is the logical config kind used by the loader.
	Kind string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	// Config API version.
	//
	// api_version identifies the document version used for compatibility over time.
	ApiVersion string `protobuf:"bytes,2,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	// Tracing settings.
	//
	// spec contains the tracing exporter settings consumed by the runtime.
	Spec          *Spec `protobuf:"bytes,3,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_config_tracing_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_config_tracing_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_config_tracing_config_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Config) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *Config) GetSpec() *Spec {
	if x != nil {
		return x.Spec
	}
	return nil
}

// Tracing settings.
//
// Spec configures tracing exporter connectivity and sampling.
type Spec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// OTLP endpoint.
	//
	// endpoint is the OTLP endpoint, for example localhost:4317 or localhost:4318.
	Endpoint *string `protobuf:"bytes,1,opt,name=endpoint,proto3,oneof" json:"endpoint,omitempty"`
	// Selected protocol.
	//
	// protocol selects the OTLP transport protocol.
	Protocol *Spec_Protocol `protobuf:"varint,2,opt,name=protocol,proto3,enum=zengo.config.tracing.Spec_Protocol,oneof" json:"protocol,omitempty"`
	// Sampling ratio.
	//
	// sampling_ratio is the trace sampling ratio in the range [0, 1].
	SamplingRatio *float64 `protobuf:"fixed64,3,opt,name=sampling_ratio,json=samplingRatio,proto3,oneof" json:"sampling_ratio,omitempty"`
	// TLS settings.
	//
	// tls configures TLS and optional mTLS for the OTLP exporter transport.
	Tls           *meta.ClientTLS `protobuf:"bytes,4,opt,name=tls,proto3" json:"tls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Spec) Reset() {
	*x = Spec{}
	mi := &file_config_tracing_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Spec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Spec) ProtoMessage() {}

func (x *Spec) ProtoReflect() protoreflect.Message {
	mi := &file_config_tracing_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Spec.ProtoReflect.Descriptor instead.
func (*Spec) Descriptor() ([]byte, []int) {
	return file_config_tracing_config_proto_rawDescGZIP(), []int{1}
}

func (x *Spec) GetEndpoint() string {
	if x != nil && x.Endpoint != nil {
		return *x.Endpoint
	}
	return ""
}

func (x *Spec) GetProtocol() Spec_Protocol {
	if x != nil && x.Protocol != nil {
		return *x.Protocol
	}
	return Spec_PROTOCOL_UNSPECIFIED
}

func (x *Spec) GetSamplingRatio() float64 {
	if x != nil && x.SamplingRatio != nil {
		return *x.SamplingRatio
	}
	return 0
}

func (x *Spec) GetTls() *meta.ClientTLS {
	if x != nil {
		return x.Tls
	}
	return nil
}

var File_config_tracing_config_proto protoreflect.FileDescriptor

const file_config_tracing_config_proto_rawDesc = "" +
	"\n" +
	"\x1bconfig/tracing/config.proto\x12\x14zengo.config.tracing\x1a\x15config/meta/tls.proto\"m\n" +
	"\x06Config\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x1f\n" +
	"\vapi_version\x18\x02 \x01(\tR\n" +
	"apiVersion\x12.\n" +
	"\x04spec\x18\x03 \x01(\v2\x1a.zengo.config.tracing.SpecR\x04spec\"\xb0\x02\n" +
	"\x04Spec\x12\x1f\n" +
	"\bendpoint\x18\x01 \x01(\tH\x00R\bendpoint\x88\x01\x01\x12D\n" +
	"\bprotocol\x18\x02 \x01(\x0e2#.zengo.config.tracing.Spec.ProtocolH\x01R\bprotocol\x88\x01\x01\x12*\n" +
	"\x0esampling_ratio\x18\x03 \x01(\x01H\x02R\rsamplingRatio\x88\x01\x01\x12.\n" +
	"\x03tls\x18\x04 \x01(\v2\x1c.zengo.config.meta.ClientTLSR\x03tls\"8\n" +
	"\bProtocol\x12\x18\n" +
	"\x14PROTOCOL_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04GRPC\x10\x01\x12\b\n" +
	"\x04HTTP\x10\x02B\v\n" +
	"\t_endpointB\v\n" +
	"\t_protocolB\x11\n" +
	"\x0f_sampling_ratioB#Z!zengo/platform/api/config/tracingb\x06proto3"

var (
	file_config_tracing_config_proto_rawDescOnce sync.Once
	file_config_tracing_config_proto_rawDescData []byte
)

func file_config_tracing_config_proto_rawDescGZIP() []byte {
	file_config_tracing_config_proto_rawDescOnce.Do(func() {
		file_config_tracing_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_config_tracing_config_proto_rawDesc), len(file_config_tracing_config_proto_rawDesc)))
	})
	return file_config_tracing_config_proto_rawDescData
}

var file_config_tracing_config_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_config_tracing_config_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_config_tracing_config_proto_goTypes = []any{
	(Spec_Protocol)(0),     // 0: zengo.config.tracing.Spec.Protocol
	(*Config)(nil),         // 1: zengo.config.tracing.Config
	(*Spec)(nil),           // 2: zengo.config.tracing.Spec
	(*meta.ClientTLS)(nil), // 3: zengo.config.meta.ClientTLS
}
var file_config_tracing_config_proto_depIdxs = []int32{
	2, // 0: zengo.config.tracing.Config.spec:type_name -> zengo.config.tracing.Spec
	0, // 1: zengo.config.tracing.Spec.protocol:type_name -> zengo.config.tracing.Spec.Protocol
	3, // 2: zengo.config.tracing.Spec.tls:type_name -> zengo.config.meta.ClientTLS
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_config_tracing_config_proto_init() }
func file_config_tracing_config_proto_init() {
	if File_config_tracing_config_proto != nil {
		return
	}
	file_config_tracing_config_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_config_tracing_config_proto_rawDesc), len(file_config_tracing_config_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_config_tracing_config_proto_goTypes,
		DependencyIndexes: file_config_tracing_config_proto_depIdxs,
		EnumInfos:         file_config_tracing_config_proto_enumTypes,
		MessageInfos:      file_config_tracing_config_proto_msgTypes,
	}.Build()
	File_config_tracing_config_proto = out.File
	file_config_tracing_config_proto_goTypes = nil
	file_config_tracing_config_proto_depIdxs = nil
}
