// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: zengo/manifest/manifest.proto

package manifestpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
	meta "zengo/platform/api/config/meta"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Legacy generation mode.
//
// Mode controls whether legacy compatibility generation is enabled.
type Compatibility_Mode int32

const (
	Compatibility_UNSPECIFIED Compatibility_Mode = 0
	Compatibility_DISABLED    Compatibility_Mode = 1
	Compatibility_ENABLED     Compatibility_Mode = 2
)

// Enum value maps for Compatibility_Mode.
var (
	Compatibility_Mode_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "DISABLED",
		2: "ENABLED",
	}
	Compatibility_Mode_value = map[string]int32{
		"UNSPECIFIED": 0,
		"DISABLED":    1,
		"ENABLED":     2,
	}
)

func (x Compatibility_Mode) Enum() *Compatibility_Mode {
	p := new(Compatibility_Mode)
	*p = x
	return p
}

func (x Compatibility_Mode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Compatibility_Mode) Descriptor() protoreflect.EnumDescriptor {
	return file_zengo_manifest_manifest_proto_enumTypes[0].Descriptor()
}

func (Compatibility_Mode) Type() protoreflect.EnumType {
	return &file_zengo_manifest_manifest_proto_enumTypes[0]
}

func (x Compatibility_Mode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Compatibility_Mode.Descriptor instead.
func (Compatibility_Mode) EnumDescriptor() ([]byte, []int) {
	return file_zengo_manifest_manifest_proto_rawDescGZIP(), []int{19, 0}
}

// Service manifest.
//
// Manifest is the top-level service infrastructure manifest loaded from zengo.* files.
type Manifest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Service identity.
	//
	// service identifies the service repository and module path.
	Service *Service `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	// Network transports.
	//
	// transports declares the network transports exposed by the service process.
	Transports *Transports `protobuf:"bytes,2,opt,name=transports,proto3" json:"transports,omitempty"`
	// Observability settings.
	//
	// observability configures metrics, tracing, and health features.
	Observability *Observability `protobuf:"bytes,5,opt,name=observability,proto3" json:"observability,omitempty"`
	// Auth settings.
	//
	// auth configures optional API-key authentication.
	Auth *Auth `protobuf:"bytes,6,opt,name=auth,proto3" json:"auth,omitempty"`
	// Database integrations.
	//
	// db declares database integrations used by the service.
	Db *DB `protobuf:"bytes,8,opt,name=db,proto3" json:"db,omitempty"`
	// Queue integrations.
	//
	// queue declares messaging integrations used by the service.
	Queue *Queue `protobuf:"bytes,9,opt,name=queue,proto3" json:"queue,omitempty"`
	// Compatibility settings.
	//
	// compatibility controls legacy version compatibility generation.
	Compatibility *Compatibility `protobuf:"bytes,10,opt,name=compatibility,proto3" json:"compatibility,omitempty"`
	// Cache integrations.
	//
	// cache declares cache integrations used by the service.
	Cache *Cache `protobuf:"bytes,11,opt,name=cache,proto3" json:"cache,omitempty"`
	// Storage integrations.
	//
	// storage declares object storage integrations used by the service.
	Storage       *Storage `protobuf:"bytes,12,opt,name=storage,proto3" json:"storage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Manifest) Reset() {
	*x = Manifest{}
	mi := &file_zengo_manifest_manifest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Manifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Manifest) ProtoMessage() {}

func (x *Manifest) ProtoReflect() protoreflect.Message {
	mi := &file_zengo_manifest_manifest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Manifest.ProtoReflect.Descriptor instead.
func (*Manifest) Descriptor() ([]byte, []int) {
	return file_zengo_manifest_manifest_proto_rawDescGZIP(), []int{0}
}

func (x *Manifest) GetService() *Service {
	if x != nil {
		return x.Service
	}
	return nil
}

func (x *Manifest) GetTransports() *Transports {
	if x != nil {
		return x.Transports
	}
	return nil
}

func (x *Manifest) GetObservability() *Observability {
	if x != nil {
		return x.Observability
	}
	return nil
}

func (x *Manifest) GetAuth() *Auth {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *Manifest) GetDb() *DB {
	if x != nil {
		return x.Db
	}
	return nil
}

func (x *Manifest) GetQueue() *Queue {
	if x != nil {
		return x.Queue
	}
	return nil
}

func (x *Manifest) GetCompatibility() *Compatibility {
	if x != nil {
		return x.Compatibility
	}
	return nil
}

func (x *Manifest) GetCache() *Cache {
	if x != nil {
		return x.Cache
	}
	return nil
}

func (x *Manifest) GetStorage() *Storage {
	if x != nil {
		return x.Storage
	}
	return nil
}

// Service identity.
//
// Service identifies a service repository.
type Service struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Service name.
	//
	// name is the logical service name used by generators and runtime helpers.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Go module path.
	//
	// module is the Go module path for the service repository.
	Module        string `protobuf:"bytes,2,opt,name=module,proto3" json:"module,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Service) Reset() {
	*x = Service{}
	mi := &file_zengo_manifest_manifest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service) ProtoMessage() {}

func (x *Service) ProtoReflect() protoreflect.Message {
	mi := &file_zengo_manifest_manifest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Service.ProtoReflect.Descriptor instead.
func (*Service) Descriptor() ([]byte, []int) {
	return file_zengo_manifest_manifest_proto_rawDescGZIP(), []int{1}
}

func (x *Service) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Service) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

// Network transports.
//
// Transports declares network-facing transports exposed by the service process.
type Transports struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// gRPC transport.
	//
	// grpc configures the gRPC transport when present.
	Grpc *GRPC `protobuf:"bytes,1,opt,name=grpc,proto3" json:"grpc,omitempty"`
	// REST transport.
	//
	// rest configures the grpc-gateway REST transport when present.
	Rest          *REST `protobuf:"bytes,2,opt,name=rest,proto3" json:"rest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transports) Reset() {
	*x = Transports{}
	mi := &file_zengo_manifest_manifest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transports) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transports) ProtoMessage() {}

func (x *Transports) ProtoReflect() protoreflect.Message {
	mi := &file_zengo_manifest_manifest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transports.ProtoReflect.Descriptor instead.
func (*Transports) Descriptor() ([]byte, []int) {
	return file_zengo_manifest_manifest_proto_rawDescGZIP(), []int{2}
}

func (x *Transports) GetGrpc() *GRPC {
	if x != nil {
		return x.Grpc
	}
	return nil
}

func (x *Transports) GetRest() *REST {
	if x != nil {
		return x.Rest
	}
	return nil
}

// gRPC transport settings.
//
// GRPC configures the gRPC transport.
type GRPC struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Listen port.
	//
	// port is the gRPC listen port.
	Port int32 `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	// TLS settings.
	//
	// tls configures server-side TLS and optional mTLS for the gRPC listener.
	Tls           *meta.ServerTLS `protobuf:"bytes,2,opt,name=tls,proto3" json:"tls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GRPC) Reset() {
	*x = GRPC{}
	mi := &file_zengo_manifest_manifest_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GRPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GRPC) ProtoMessage() {}

func (x *GRPC) ProtoReflect() protoreflect.Message {
	mi := &file_zengo_manifest_manifest_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GRPC.ProtoReflect.Descriptor instead.
func (*GRPC) Descriptor() ([]byte, []int) {
	return file_zengo_manifest_manifest_proto_rawDescGZIP(), []int{3}
}

func (x *GRPC) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *GRPC) GetTls() *meta.ServerTLS {
	if x != nil {
		return x.Tls
	}
	return nil
}

// REST transport settings.
//
// REST configures the REST transport.
type REST struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Listen port.
	//
	// port is the HTTP listen port.
	Port int32 `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	// TLS settings.
	//
	// tls configures server-side TLS and optional mTLS for the REST listener.
	Tls *meta.ServerTLS `protobuf:"bytes,2,opt,name=tls,proto3" json:"tls,omitempty"`
	// Gateway gRPC client TLS.
	//
	// grpc_client_tls configures TLS used by grpc-gateway when it dials the local gRPC listener.
	GrpcClientTls *meta.ClientTLS `protobuf:"bytes,3,opt,name=grpc_client_tls,json=grpcClientTls,proto3" json:"grpc_client_tls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *REST) Reset() {
	*x = REST{}
	mi := &file_zengo_manifest_manifest_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *REST) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*REST) ProtoMessage() {}

func (x *REST) ProtoReflect() protoreflect.Message {
	mi := &file_zengo_manifest_manifest_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use REST.ProtoReflect.Descriptor instead.
func (*REST) Descriptor() ([]byte, []int) {
	return file_zengo_manifest_manifest_proto_rawDescGZIP(), []int{4}
}

func (x *REST) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *REST) GetTls() *meta.ServerTLS {
	if x != nil {
		return x.Tls
	}
	return nil
}

func (x *REST) GetGrpcClientTls() *meta.ClientTLS {
	if x != nil {
		return x.GrpcClientTls
	}
	return nil
}

// Database integrations.
//
// DB groups relational and wide-column database integrations.
type DB struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// PostgreSQL integration.
	//
	// postgres configures PostgreSQL integration.
	Postgres *PostgresDB `protobuf:"bytes,1,opt,name=postgres,proto3" json:"postgres,omitempty"`
	// Cassandra integration.
	//
	// cassandra configures Cassandra integration.
	Cassandra *CassandraDB `protobuf:"bytes,2,opt,name=cassandra,proto3" json:"cassandra,omitempty"`
	// Oracle integration.
	//
	// oracle configures Oracle integration.
	Oracle        *OracleDB `protobuf:"bytes,3,opt,name=oracle,proto3" json:"oracle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DB) Reset() {
	*x = DB{}
	mi := &file_zengo_manifest_manifest_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DB) ProtoMessage() {}

func (x *DB) ProtoReflect() protoreflect.Message {
	mi := &file_zengo_manifest_manifest_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DB.ProtoReflect.Descriptor instead.
func (*DB) Descriptor() ([]byte, []int) {
	return file_zengo_manifest_manifest_proto_rawDescGZIP(), []int{5}
}

func (x *DB) GetPostgres() *PostgresDB {
	if x != nil {
		return x.Postgres
	}
	return nil
}

func (x *DB) GetCassandra() *CassandraDB {
	if x != nil {
		return x.Cassandra
	}
	return nil
}

func (x *DB) GetOracle() *OracleDB {
	if x != nil {
		return x.Oracle
	}
	return nil
}

// PostgreSQL integration settings.
//
// PostgresDB configures PostgreSQL integration.
type PostgresDB struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Config source kind.
	//
	// config_from overrides the typed config kind to load. The default kind is postgres.
	ConfigFrom string `protobuf:"bytes,1,opt,name=config_from,json=configFrom,proto3" json:"config_from,omitempty"`
	// Query directory.
	//
	// queries points to the sqlc query directory.
	Queries       string `protobuf:"bytes,2,opt,name=queries,proto3" json:"queries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostgresDB) Reset() {
	*x = PostgresDB{}
	mi := &file_zengo_manifest_manifest_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostgresDB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostgresDB) ProtoMessage() {}

func (x *PostgresDB) ProtoReflect() protoreflect.Message {
	mi := &file_zengo_manifest_manifest_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostgresDB.ProtoReflect.Descriptor instead.
func (*PostgresDB) Descriptor() ([]byte, []int) {
	return file_zengo_manifest_manifest_proto_rawDescGZIP(), []int{6}
}

func (x *PostgresDB) GetConfigFrom() string {
	if x != nil {
		return x.ConfigFrom
	}
	return ""
}

func (x *PostgresDB) GetQueries() string {
	if x != nil {
		return x.Queries
	}
	return ""
}

// Cassandra integration settings.
//
// CassandraDB configures Cassandra integration.
type CassandraDB struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Config source kind.
	//
	// config_from overrides the typed config kind to load.
	ConfigFrom string `protobuf:"bytes,1,opt,name=config_from,json=configFrom,proto3" json:"config_from,omitempty"`
	// Keyspace name.
	//
	// keyspace is the logical Cassandra keyspace used by the service.
	Keyspace string `protobuf:"bytes,2,opt,name=keyspace,proto3" json:"keyspace,omitempty"`
	// CQL directory.
	//
	// cql points to the CQL query directory.
	Cql           string `protobuf:"bytes,3,opt,name=cql,proto3" json:"cql,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CassandraDB) Reset() {
	*x = CassandraDB{}
	mi := &file_zengo_manifest_manifest_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CassandraDB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CassandraDB) ProtoMessage() {}

func (x *CassandraDB) ProtoReflect() protoreflect.Message {
	mi := &file_zengo_manifest_manifest_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CassandraDB.ProtoReflect.Descriptor instead.
func (*CassandraDB) Descriptor() ([]byte, []int) {
	return file_zengo_manifest_manifest_proto_rawDescGZIP(), []int{7}
}

func (x *CassandraDB) GetConfigFrom() string {
	if x != nil {
		return x.ConfigFrom
	}
	return ""
}

func (x *CassandraDB) GetKeyspace() string {
	if x != nil {
		return x.Keyspace
	}
	return ""
}

func (x *CassandraDB) GetCql() string {
	if x != nil {
		return x.Cql
	}
	return ""
}

// Oracle integration settings.
//
// OracleDB configures Oracle integration.
type OracleDB struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Config source kind.
	//
	// config_from overrides the typed config kind to load.
	ConfigFrom string `protobuf:"bytes,1,opt,name=config_from,json=configFrom,proto3" json:"config_from,omitempty"`
	// Query directory.
	//
	// queries points to the sqlc query directory.
	Queries       string `protobuf:"bytes,2,opt,name=queries,proto3" json:"queries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OracleDB) Reset() {
	*x = OracleDB{}
	mi := &file_zengo_manifest_manifest_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OracleDB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OracleDB) ProtoMessage() {}

func (x *OracleDB) ProtoReflect() protoreflect.Message {
	mi := &file_zengo_manifest_manifest_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OracleDB.ProtoReflect.Descriptor instead.
func (*OracleDB) Descriptor() ([]byte, []int) {
	return file_zengo_manifest_manifest_proto_rawDescGZIP(), []int{8}
}

func (x *OracleDB) GetConfigFrom() string {
	if x != nil {
		return x.ConfigFrom
	}
	return ""
}

func (x *OracleDB) GetQueries() string {
	if x != nil {
		return x.Queries
	}
	return ""
}

// Queue integrations.
//
// Queue groups message broker integrations.
type Queue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Kafka integration.
	//
	// kafka configures Kafka integration.
	Kafka *Kafka `protobuf:"bytes,1,opt,name=kafka,proto3" json:"kafka,omitempty"`
	// NATS integration.
	//
	// nats configures NATS integration.
	Nats *Nats `protobuf:"bytes,2,opt,name=nats,proto3" json:"nats,omitempty"`
	// RabbitMQ integration.
	//
	// rabbitmq configures RabbitMQ integration.
	Rabbitmq      *RabbitMQ `protobuf:"bytes,3,opt,name=rabbitmq,proto3" json:"rabbitmq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Queue) Reset() {
	*x = Queue{}
	mi := &file_zengo_manifest_manifest_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Queue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Queue) ProtoMessage() {}

func (x *Queue) ProtoReflect() protoreflect.Message {
	mi := &file_zengo_manifest_manifest_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Queue.ProtoReflect.Descriptor instead.
func (*Queue) Descriptor() ([]byte, []int) {
	return file_zengo_manifest_manifest_proto_rawDescGZIP(), []int{9}
}

func (x *Queue) GetKafka() *Kafka {
	if x != nil {
		return x.Kafka
	}
	return nil
}

func (x *Queue) GetNats() *Nats {
	if x != nil {
		return x.Nats
	}
	return nil
}

func (x *Queue) GetRabbitmq() *RabbitMQ {
	if x != nil {
		return x.Rabbitmq
	}
	return nil
}

// Cache integrations.
//
// Cache groups cache integrations.
type Cache struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Redis integration.
	//
	// redis configures Redis integration.
	Redis         *Redis `protobuf:"bytes,1,opt,name=redis,proto3" json:"redis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cache) Reset() {
	*x = Cache{}
	mi := &file_zengo_manifest_manifest_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cache) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cache) ProtoMessage() {}

func (x *Cache) ProtoReflect() protoreflect.Message {
	mi := &file_zengo_manifest_manifest_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cache.ProtoReflect.Descriptor instead.
func (*Cache) Descriptor() ([]byte, []int) {
	return file_zengo_manifest_manifest_proto_rawDescGZIP(), []int{10}
}

func (x *Cache) GetRedis() *Redis {
	if x != nil {
		return x.Redis
	}
	return nil
}

// Storage integrations.
//
// Storage groups object storage integrations.
type Storage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// S3 integration.
	//
	// s3 configures S3-compatible storage integration.
	S3            *S3 `protobuf:"bytes,1,opt,name=s3,proto3" json:"s3,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Storage) Reset() {
	*x = Storage{}
	mi := &file_zengo_manifest_manifest_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Storage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Storage) ProtoMessage() {}

func (x *Storage) ProtoReflect() protoreflect.Message {
	mi := &file_zengo_manifest_manifest_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Storage.ProtoReflect.Descriptor instead.
func (*Storage) Descriptor() ([]byte, []int) {
	return file_zengo_manifest_manifest_proto_rawDescGZIP(), []int{11}
}

func (x *Storage) GetS3() *S3 {
	if x != nil {
		return x.S3
	}
	return nil
}

// Kafka integration settings.
//
// Kafka configures Kafka integration.
type Kafka struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Broker config kind.
	//
	// brokers_from_config overrides the typed config kind to load.
	BrokersFromConfig string `protobuf:"bytes,1,opt,name=brokers_from_config,json=brokersFromConfig,proto3" json:"brokers_from_config,omitempty"`
	// Fallback brokers.
	//
	// brokers supplies manifest-level fallback broker addresses.
	Brokers       []string `protobuf:"bytes,2,rep,name=brokers,proto3" json:"brokers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Kafka) Reset() {
	*x = Kafka{}
	mi := &file_zengo_manifest_manifest_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Kafka) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Kafka) ProtoMessage() {}

func (x *Kafka) ProtoReflect() protoreflect.Message {
	mi := &file_zengo_manifest_manifest_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Kafka.ProtoReflect.Descriptor instead.
func (*Kafka) Descriptor() ([]byte, []int) {
	return file_zengo_manifest_manifest_proto_rawDescGZIP(), []int{12}
}

func (x *Kafka) GetBrokersFromConfig() string {
	if x != nil {
		return x.BrokersFromConfig
	}
	return ""
}

func (x *Kafka) GetBrokers() []string {
	if x != nil {
		return x.Brokers
	}
	return nil
}

// RabbitMQ integration settings.
//
// RabbitMQ configures RabbitMQ integration.
type RabbitMQ struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Config source kind.
	//
	// config_from overrides the typed config kind to load.
	ConfigFrom string `protobuf:"bytes,1,opt,name=config_from,json=configFrom,proto3" json:"config_from,omitempty"`
	// Fallback URLs.
	//
	// urls supplies manifest-level fallback connection URLs.
	Urls          []string `protobuf:"bytes,2,rep,name=urls,proto3" json:"urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RabbitMQ) Reset() {
	*x = RabbitMQ{}
	mi := &file_zengo_manifest_manifest_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RabbitMQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RabbitMQ) ProtoMessage() {}

func (x *RabbitMQ) ProtoReflect() protoreflect.Message {
	mi := &file_zengo_manifest_manifest_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RabbitMQ.ProtoReflect.Descriptor instead.
func (*RabbitMQ) Descriptor() ([]byte, []int) {
	return file_zengo_manifest_manifest_proto_rawDescGZIP(), []int{13}
}

func (x *RabbitMQ) GetConfigFrom() string {
	if x != nil {
		return x.ConfigFrom
	}
	return ""
}

func (x *RabbitMQ) GetUrls() []string {
	if x != nil {
		return x.Urls
	}
	return nil
}

// Redis integration settings.
//
// Redis configures Redis integration.
type Redis struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Config source kind.
	//
	// config_from overrides the typed config kind to load.
	ConfigFrom    string `protobuf:"bytes,1,opt,name=config_from,json=configFrom,proto3" json:"config_from,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Redis) Reset() {
	*x = Redis{}
	mi := &file_zengo_manifest_manifest_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Redis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Redis) ProtoMessage() {}

func (x *Redis) ProtoReflect() protoreflect.Message {
	mi := &file_zengo_manifest_manifest_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Redis.ProtoReflect.Descriptor instead.
func (*Redis) Descriptor() ([]byte, []int) {
	return file_zengo_manifest_manifest_proto_rawDescGZIP(), []int{14}
}

func (x *Redis) GetConfigFrom() string {
	if x != nil {
		return x.ConfigFrom
	}
	return ""
}

// NATS integration settings.
//
// Nats configures NATS integration.
type Nats struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Config source kind.
	//
	// config_from overrides the typed config kind to load.
	ConfigFrom string `protobuf:"bytes,1,opt,name=config_from,json=configFrom,proto3" json:"config_from,omitempty"`
	// Fallback URLs.
	//
	// urls supplies manifest-level fallback server URLs.
	Urls          []string `protobuf:"bytes,2,rep,name=urls,proto3" json:"urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Nats) Reset() {
	*x = Nats{}
	mi := &file_zengo_manifest_manifest_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Nats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Nats) ProtoMessage() {}

func (x *Nats) ProtoReflect() protoreflect.Message {
	mi := &file_zengo_manifest_manifest_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Nats.ProtoReflect.Descriptor instead.
func (*Nats) Descriptor() ([]byte, []int) {
	return file_zengo_manifest_manifest_proto_rawDescGZIP(), []int{15}
}

func (x *Nats) GetConfigFrom() string {
	if x != nil {
		return x.ConfigFrom
	}
	return ""
}

func (x *Nats) GetUrls() []string {
	if x != nil {
		return x.Urls
	}
	return nil
}

// S3 integration settings.
//
// S3 configures S3-compatible object storage integration.
type S3 struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Config source kind.
	//
	// config_from overrides the typed config kind to load.
	ConfigFrom    string `protobuf:"bytes,1,opt,name=config_from,json=configFrom,proto3" json:"config_from,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S3) Reset() {
	*x = S3{}
	mi := &file_zengo_manifest_manifest_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S3) ProtoMessage() {}

func (x *S3) ProtoReflect() protoreflect.Message {
	mi := &file_zengo_manifest_manifest_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S3.ProtoReflect.Descriptor instead.
func (*S3) Descriptor() ([]byte, []int) {
	return file_zengo_manifest_manifest_proto_rawDescGZIP(), []int{16}
}

func (x *S3) GetConfigFrom() string {
	if x != nil {
		return x.ConfigFrom
	}
	return ""
}

// Observability settings.
//
// Observability configures runtime observability features.
type Observability struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Metrics flag.
	//
	// metrics enables metrics collection and the /metrics endpoint.
	Metrics bool `protobuf:"varint,1,opt,name=metrics,proto3" json:"metrics,omitempty"`
	// Tracing flag.
	//
	// tracing enables distributed tracing.
	Tracing bool `protobuf:"varint,2,opt,name=tracing,proto3" json:"tracing,omitempty"`
	// Health flag.
	//
	// health enables readiness checks in generated runtime wiring.
	Health bool `protobuf:"varint,3,opt,name=health,proto3" json:"health,omitempty"`
	// Tracing config kind.
	//
	// tracing_config_from overrides the tracing config kind to load.
	TracingConfigFrom string `protobuf:"bytes,4,opt,name=tracing_config_from,json=tracingConfigFrom,proto3" json:"tracing_config_from,omitempty"`
	// Logging config kind.
	//
	// logging_config_from overrides the logging config kind to load.
	LoggingConfigFrom string `protobuf:"bytes,5,opt,name=logging_config_from,json=loggingConfigFrom,proto3" json:"logging_config_from,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Observability) Reset() {
	*x = Observability{}
	mi := &file_zengo_manifest_manifest_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Observability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Observability) ProtoMessage() {}

func (x *Observability) ProtoReflect() protoreflect.Message {
	mi := &file_zengo_manifest_manifest_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Observability.ProtoReflect.Descriptor instead.
func (*Observability) Descriptor() ([]byte, []int) {
	return file_zengo_manifest_manifest_proto_rawDescGZIP(), []int{17}
}

func (x *Observability) GetMetrics() bool {
	if x != nil {
		return x.Metrics
	}
	return false
}

func (x *Observability) GetTracing() bool {
	if x != nil {
		return x.Tracing
	}
	return false
}

func (x *Observability) GetHealth() bool {
	if x != nil {
		return x.Health
	}
	return false
}

func (x *Observability) GetTracingConfigFrom() string {
	if x != nil {
		return x.TracingConfigFrom
	}
	return ""
}

func (x *Observability) GetLoggingConfigFrom() string {
	if x != nil {
		return x.LoggingConfigFrom
	}
	return ""
}

// Auth settings.
//
// Auth configures API-key authentication.
type Auth struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Enabled flag.
	//
	// enabled toggles the auth layer on or off.
	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// API keys.
	//
	// api_keys maps logical names to API key values.
	ApiKeys       map[string]string `protobuf:"bytes,2,rep,name=api_keys,json=apiKeys,proto3" json:"api_keys,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Auth) Reset() {
	*x = Auth{}
	mi := &file_zengo_manifest_manifest_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Auth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Auth) ProtoMessage() {}

func (x *Auth) ProtoReflect() protoreflect.Message {
	mi := &file_zengo_manifest_manifest_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Auth.ProtoReflect.Descriptor instead.
func (*Auth) Descriptor() ([]byte, []int) {
	return file_zengo_manifest_manifest_proto_rawDescGZIP(), []int{18}
}

func (x *Auth) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Auth) GetApiKeys() map[string]string {
	if x != nil {
		return x.ApiKeys
	}
	return nil
}

// Compatibility settings.
//
// Compatibility controls whether discovered legacy versions participate in generation.
type Compatibility struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Legacy version mode.
	//
	// legacy_versions controls whether discovered legacy versions are generated.
	LegacyVersions Compatibility_Mode `protobuf:"varint,1,opt,name=legacy_versions,json=legacyVersions,proto3,enum=zengo.manifest.Compatibility_Mode" json:"legacy_versions,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Compatibility) Reset() {
	*x = Compatibility{}
	mi := &file_zengo_manifest_manifest_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Compatibility) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Compatibility) ProtoMessage() {}

func (x *Compatibility) ProtoReflect() protoreflect.Message {
	mi := &file_zengo_manifest_manifest_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Compatibility.ProtoReflect.Descriptor instead.
func (*Compatibility) Descriptor() ([]byte, []int) {
	return file_zengo_manifest_manifest_proto_rawDescGZIP(), []int{19}
}

func (x *Compatibility) GetLegacyVersions() Compatibility_Mode {
	if x != nil {
		return x.LegacyVersions
	}
	return Compatibility_UNSPECIFIED
}

var File_zengo_manifest_manifest_proto protoreflect.FileDescriptor

const file_zengo_manifest_manifest_proto_rawDesc = "" +
	"\n" +
	"\x1dzengo/manifest/manifest.proto\x12\x0ezengo.manifest\x1a\x15config/meta/tls.proto\"\xe4\x03\n" +
	"\bManifest\x121\n" +
	"\aservice\x18\x01 \x01(\v2\x17.zengo.manifest.ServiceR\aservice\x12:\n" +
	"\n" +
	"transports\x18\x02 \x01(\v2\x1a.zengo.manifest.TransportsR\n" +
	"transports\x12C\n" +
	"\robservability\x18\x05 \x01(\v2\x1d.zengo.manifest.ObservabilityR\robservability\x12(\n" +
	"\x04auth\x18\x06 \x01(\v2\x14.zengo.manifest.AuthR\x04auth\x12\"\n" +
	"\x02db\x18\b \x01(\v2\x12.zengo.manifest.DBR\x02db\x12+\n" +
	"\x05queue\x18\t \x01(\v2\x15.zengo.manifest.QueueR\x05queue\x12C\n" +
	"\rcompatibility\x18\n" +
	" \x01(\v2\x1d.zengo.manifest.CompatibilityR\rcompatibility\x12+\n" +
	"\x05cache\x18\v \x01(\v2\x15.zengo.manifest.CacheR\x05cache\x121\n" +
	"\astorage\x18\f \x01(\v2\x17.zengo.manifest.StorageR\astorageJ\x04\b\a\x10\b\"5\n" +
	"\aService\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06module\x18\x02 \x01(\tR\x06module\"`\n" +
	"\n" +
	"Transports\x12(\n" +
	"\x04grpc\x18\x01 \x01(\v2\x14.zengo.manifest.GRPCR\x04grpc\x12(\n" +
	"\x04rest\x18\x02 \x01(\v2\x14.zengo.manifest.RESTR\x04rest\"J\n" +
	"\x04GRPC\x12\x12\n" +
	"\x04port\x18\x01 \x01(\x05R\x04port\x12.\n" +
	"\x03tls\x18\x02 \x01(\v2\x1c.zengo.config.meta.ServerTLSR\x03tls\"\x90\x01\n" +
	"\x04REST\x12\x12\n" +
	"\x04port\x18\x01 \x01(\x05R\x04port\x12.\n" +
	"\x03tls\x18\x02 \x01(\v2\x1c.zengo.config.meta.ServerTLSR\x03tls\x12D\n" +
	"\x0fgrpc_client_tls\x18\x03 \x01(\v2\x1c.zengo.config.meta.ClientTLSR\rgrpcClientTls\"\xa9\x01\n" +
	"\x02DB\x126\n" +
	"\bpostgres\x18\x01 \x01(\v2\x1a.zengo.manifest.PostgresDBR\bpostgres\x129\n" +
	"\tcassandra\x18\x02 \x01(\v2\x1b.zengo.manifest.CassandraDBR\tcassandra\x120\n" +
	"\x06oracle\x18\x03 \x01(\v2\x18.zengo.manifest.OracleDBR\x06oracle\"G\n" +
	"\n" +
	"PostgresDB\x12\x1f\n" +
	"\vconfig_from\x18\x01 \x01(\tR\n" +
	"configFrom\x12\x18\n" +
	"\aqueries\x18\x02 \x01(\tR\aqueries\"\\\n" +
	"\vCassandraDB\x12\x1f\n" +
	"\vconfig_from\x18\x01 \x01(\tR\n" +
	"configFrom\x12\x1a\n" +
	"\bkeyspace\x18\x02 \x01(\tR\bkeyspace\x12\x10\n" +
	"\x03cql\x18\x03 \x01(\tR\x03cql\"E\n" +
	"\bOracleDB\x12\x1f\n" +
	"\vconfig_from\x18\x01 \x01(\tR\n" +
	"configFrom\x12\x18\n" +
	"\aqueries\x18\x02 \x01(\tR\aqueries\"\x94\x01\n" +
	"\x05Queue\x12+\n" +
	"\x05kafka\x18\x01 \x01(\v2\x15.zengo.manifest.KafkaR\x05kafka\x12(\n" +
	"\x04nats\x18\x02 \x01(\v2\x14.zengo.manifest.NatsR\x04nats\x124\n" +
	"\brabbitmq\x18\x03 \x01(\v2\x18.zengo.manifest.RabbitMQR\brabbitmq\"4\n" +
	"\x05Cache\x12+\n" +
	"\x05redis\x18\x01 \x01(\v2\x15.zengo.manifest.RedisR\x05redis\"-\n" +
	"\aStorage\x12\"\n" +
	"\x02s3\x18\x01 \x01(\v2\x12.zengo.manifest.S3R\x02s3\"Q\n" +
	"\x05Kafka\x12.\n" +
	"\x13brokers_from_config\x18\x01 \x01(\tR\x11brokersFromConfig\x12\x18\n" +
	"\abrokers\x18\x02 \x03(\tR\abrokers\"?\n" +
	"\bRabbitMQ\x12\x1f\n" +
	"\vconfig_from\x18\x01 \x01(\tR\n" +
	"configFrom\x12\x12\n" +
	"\x04urls\x18\x02 \x03(\tR\x04urls\"(\n" +
	"\x05Redis\x12\x1f\n" +
	"\vconfig_from\x18\x01 \x01(\tR\n" +
	"configFrom\";\n" +
	"\x04Nats\x12\x1f\n" +
	"\vconfig_from\x18\x01 \x01(\tR\n" +
	"configFrom\x12\x12\n" +
	"\x04urls\x18\x02 \x03(\tR\x04urls\"%\n" +
	"\x02S3\x12\x1f\n" +
	"\vconfig_from\x18\x01 \x01(\tR\n" +
	"configFrom\"\xbb\x01\n" +
	"\rObservability\x12\x18\n" +
	"\ametrics\x18\x01 \x01(\bR\ametrics\x12\x18\n" +
	"\atracing\x18\x02 \x01(\bR\atracing\x12\x16\n" +
	"\x06health\x18\x03 \x01(\bR\x06health\x12.\n" +
	"\x13tracing_config_from\x18\x04 \x01(\tR\x11tracingConfigFrom\x12.\n" +
	"\x13logging_config_from\x18\x05 \x01(\tR\x11loggingConfigFrom\"\x9a\x01\n" +
	"\x04Auth\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12<\n" +
	"\bapi_keys\x18\x02 \x03(\v2!.zengo.manifest.Auth.ApiKeysEntryR\aapiKeys\x1a:\n" +
	"\fApiKeysEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x90\x01\n" +
	"\rCompatibility\x12K\n" +
	"\x0flegacy_versions\x18\x01 \x01(\x0e2\".zengo.manifest.Compatibility.ModeR\x0elegacyVersions\"2\n" +
	"\x04Mode\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\f\n" +
	"\bDISABLED\x10\x01\x12\v\n" +
	"\aENABLED\x10\x02B.Z,zengo/platform/api/zengo/manifest;manifestpbb\x06proto3"

var (
	file_zengo_manifest_manifest_proto_rawDescOnce sync.Once
	file_zengo_manifest_manifest_proto_rawDescData []byte
)

func file_zengo_manifest_manifest_proto_rawDescGZIP() []byte {
	file_zengo_manifest_manifest_proto_rawDescOnce.Do(func() {
		file_zengo_manifest_manifest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_zengo_manifest_manifest_proto_rawDesc), len(file_zengo_manifest_manifest_proto_rawDesc)))
	})
	return file_zengo_manifest_manifest_proto_rawDescData
}

var file_zengo_manifest_manifest_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_zengo_manifest_manifest_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_zengo_manifest_manifest_proto_goTypes = []any{
	(Compatibility_Mode)(0), // 0: zengo.manifest.Compatibility.Mode
	(*Manifest)(nil),        // 1: zengo.manifest.Manifest
	(*Service)(nil),         // 2: zengo.manifest.Service
	(*Transports)(nil),      // 3: zengo.manifest.Transports
	(*GRPC)(nil),            // 4: zengo.manifest.GRPC
	(*REST)(nil),            // 5: zengo.manifest.REST
	(*DB)(nil),              // 6: zengo.manifest.DB
	(*PostgresDB)(nil),      // 7: zengo.manifest.PostgresDB
	(*CassandraDB)(nil),     // 8: zengo.manifest.CassandraDB
	(*OracleDB)(nil),        // 9: zengo.manifest.OracleDB
	(*Queue)(nil),           // 10: zengo.manifest.Queue
	(*Cache)(nil),           // 11: zengo.manifest.Cache
	(*Storage)(nil),         // 12: zengo.manifest.Storage
	(*Kafka)(nil),           // 13: zengo.manifest.Kafka
	(*RabbitMQ)(nil),        // 14: zengo.manifest.RabbitMQ
	(*Redis)(nil),           // 15: zengo.manifest.Redis
	(*Nats)(nil),            // 16: zengo.manifest.Nats
	(*S3)(nil),              // 17: zengo.manifest.S3
	(*Observability)(nil),   // 18: zengo.manifest.Observability
	(*Auth)(nil),            // 19: zengo.manifest.Auth
	(*Compatibility)(nil),   // 20: zengo.manifest.Compatibility
	nil,                     // 21: zengo.manifest.Auth.ApiKeysEntry
	(*meta.ServerTLS)(nil),  // 22: zengo.config.meta.ServerTLS
	(*meta.ClientTLS)(nil),  // 23: zengo.config.meta.ClientTLS
}
var file_zengo_manifest_manifest_proto_depIdxs = []int32{
	2,  // 0: zengo.manifest.Manifest.service:type_name -> zengo.manifest.Service
	3,  // 1: zengo.manifest.Manifest.transports:type_name -> zengo.manifest.Transports
	18, // 2: zengo.manifest.Manifest.observability:type_name -> zengo.manifest.Observability
	19, // 3: zengo.manifest.Manifest.auth:type_name -> zengo.manifest.Auth
	6,  // 4: zengo.manifest.Manifest.db:type_name -> zengo.manifest.DB
	10, // 5: zengo.manifest.Manifest.queue:type_name -> zengo.manifest.Queue
	20, // 6: zengo.manifest.Manifest.compatibility:type_name -> zengo.manifest.Compatibility
	11, // 7: zengo.manifest.Manifest.cache:type_name -> zengo.manifest.Cache
	12, // 8: zengo.manifest.Manifest.storage:type_name -> zengo.manifest.Storage
	4,  // 9: zengo.manifest.Transports.grpc:type_name -> zengo.manifest.GRPC
	5,  // 10: zengo.manifest.Transports.rest:type_name -> zengo.manifest.REST
	22, // 11: zengo.manifest.GRPC.tls:type_name -> zengo.config.meta.ServerTLS
	22, // 12: zengo.manifest.REST.tls:type_name -> zengo.config.meta.ServerTLS
	23, // 13: zengo.manifest.REST.grpc_client_tls:type_name -> zengo.config.meta.ClientTLS
	7,  // 14: zengo.manifest.DB.postgres:type_name -> zengo.manifest.PostgresDB
	8,  // 15: zengo.manifest.DB.cassandra:type_name -> zengo.manifest.CassandraDB
	9,  // 16: zengo.manifest.DB.oracle:type_name -> zengo.manifest.OracleDB
	13, // 17: zengo.manifest.Queue.kafka:type_name -> zengo.manifest.Kafka
	16, // 18: zengo.manifest.Queue.nats:type_name -> zengo.manifest.Nats
	14, // 19: zengo.manifest.Queue.rabbitmq:type_name -> zengo.manifest.RabbitMQ
	15, // 20: zengo.manifest.Cache.redis:type_name -> zengo.manifest.Redis
	17, // 21: zengo.manifest.Storage.s3:type_name -> zengo.manifest.S3
	21, // 22: zengo.manifest.Auth.api_keys:type_name -> zengo.manifest.Auth.ApiKeysEntry
	0,  // 23: zengo.manifest.Compatibility.legacy_versions:type_name -> zengo.manifest.Compatibility.Mode
	24, // [24:24] is the sub-list for method output_type
	24, // [24:24] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_zengo_manifest_manifest_proto_init() }
func file_zengo_manifest_manifest_proto_init() {
	if File_zengo_manifest_manifest_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_zengo_manifest_manifest_proto_rawDesc), len(file_zengo_manifest_manifest_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_zengo_manifest_manifest_proto_goTypes,
		DependencyIndexes: file_zengo_manifest_manifest_proto_depIdxs,
		EnumInfos:         file_zengo_manifest_manifest_proto_enumTypes,
		MessageInfos:      file_zengo_manifest_manifest_proto_msgTypes,
	}.Build()
	File_zengo_manifest_manifest_proto = out.File
	file_zengo_manifest_manifest_proto_goTypes = nil
	file_zengo_manifest_manifest_proto_depIdxs = nil
}
