package main

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"os/exec"
	"path/filepath"
	"slices"
	"strings"
	"zengo/platform/internal/cqlgen"
	"zengo/platform/internal/generator"
	"zengo/platform/internal/manifest"
	"zengo/platform/internal/versioning"
)

const generatedMainHeader = "// Code generated by zengo gen. DO NOT EDIT."

func fail(exitCode int, message string, args ...any) {
	_, _ = fmt.Fprintf(os.Stderr, message, args...)
	_, _ = fmt.Fprintln(os.Stderr)
	os.Exit(exitCode)
}

// runCommand executes a command in the current working directory with stdio attached.
func runCommand(ctx context.Context, name string, args ...string) error {
	cmd := exec.CommandContext(ctx, name, args...)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	return cmd.Run()
}

// runCommandDir executes a command in dir with stdio attached.
func runCommandDir(ctx context.Context, dir, name string, args ...string) error {
	cmd := exec.CommandContext(ctx, name, args...)
	cmd.Dir = dir
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	return cmd.Run()
}

// fileExists reports whether path exists.
func fileExists(path string) bool {
	_, err := os.Stat(path)
	return err == nil
}

// isServiceRootAt reports whether dir looks like a Zengo service root.
func isServiceRootAt(dir string) bool {
	if slices.ContainsFunc(
		[]string{
			"zengo.yaml",
			"zengo.yml",
			"zengo.textproto",
			"zengo.pbtxt",
		},
		func(name string) bool {
			return fileExists(filepath.Join(dir, name))
		}) {
		return true
	}
	return fileExists(
		filepath.Join(dir, "buf.gen.yaml")) &&
		fileExists(filepath.Join(dir, "api"))
}

// resolveServicePaths resolves the service root and manifest path for a command invocation.
func resolveServicePaths(rootDir, manifestPath string) (servicePaths, error) {
	if manifestPath != "" {
		absManifest, err := filepath.Abs(manifestPath)
		if err != nil {
			return servicePaths{}, err
		}
		return servicePaths{
			rootDir:      filepath.Dir(absManifest),
			manifestPath: absManifest,
		}, nil
	}
	absRoot, err := resolveRootDir(rootDir, "")
	if err != nil {
		return servicePaths{}, err
	}
	var resolvedManifest string

	resolvedManifest, err = manifest.FindPath(absRoot)
	if err != nil {
		return servicePaths{}, err
	}
	return servicePaths{
		rootDir:      absRoot,
		manifestPath: resolvedManifest,
	}, nil
}

// resolveRootDir resolves the service root directory from either --dir or --manifest.
func resolveRootDir(rootDir, manifestPath string) (string, error) {
	if manifestPath != "" {
		absManifest, err := filepath.Abs(manifestPath)
		if err != nil {
			return "", err
		}
		return filepath.Dir(absManifest), nil
	}
	if rootDir == "" {
		rootDir = "."
	}
	return filepath.Abs(rootDir)
}

type genOptions struct {
	ctx       context.Context
	skipBuf   bool
	protoOnly bool
	wireOnly  bool
	skipSQLC  bool
	skipCQL   bool
	skipMain  bool
	forceMain bool
	quietMain bool
}

type servicePaths struct {
	rootDir      string
	manifestPath string
}

// runGenerateAll runs the full generation pipeline, including generated main artifacts.
func runGenerateAll(rootDir, manifestPath string, o genOptions) error {
	err := runGenerateOptsIn(rootDir, manifestPath, o)
	if err != nil {
		return err
	}
	if o.protoOnly || o.wireOnly {
		return nil
	}
	return runGenerateMainOptsIn(rootDir, manifestPath, o)
}

// runGenerateOptsIn runs the non-main generation stages inside the resolved service root.
func runGenerateOptsIn(rootDir, manifestPath string, o genOptions) error {
	ctx := o.ctx
	if ctx == nil {
		ctx = context.Background()
	}
	resolvedRoot, err := resolveRootDir(rootDir, manifestPath)
	if err != nil {
		return err
	}
	if o.protoOnly {
		err = runCommandDir(ctx, resolvedRoot, "buf", "generate")
		if err != nil {
			return fmt.Errorf("buf generate: %w", err)
		}
		err = generator.SplitOpenAPIAt(resolvedRoot)
		if err != nil {
			return fmt.Errorf("openapi split: %w", err)
		}
		return nil
	}
	if !o.skipBuf && !o.wireOnly {
		err = runCommandDir(ctx, resolvedRoot, "buf", "generate")
		if err != nil {
			return fmt.Errorf("buf generate: %w", err)
		}
		err = generator.SplitOpenAPIAt(resolvedRoot)
		if err != nil {
			return fmt.Errorf("openapi split: %w", err)
		}
	} else if o.skipBuf && !o.wireOnly {
		err = generator.SplitOpenAPIAt(resolvedRoot)
		if err != nil {
			return fmt.Errorf("openapi split: %w", err)
		}
	}
	if o.wireOnly || !o.protoOnly {
		var paths servicePaths
		paths, err = resolveServicePaths(rootDir, manifestPath)
		if err != nil {
			return err
		}
		var m *manifest.Manifest
		m, err = manifest.Load(paths.manifestPath)
		if err != nil {
			return fmt.Errorf("manifest load: %w", err)
		}
		module := versioning.ReadModuleAt(filepath.Join(resolvedRoot, "go.mod"))
		if module == "" {
			return fmt.Errorf("could not read module from go.mod")
		}
		err = versioning.Generate(versioning.GenerateOptions{
			Module:   module,
			APIRoot:  pathFromWorkingDir(filepath.Join(resolvedRoot, "api")),
			GenDir:   pathFromWorkingDir(filepath.Join(resolvedRoot, "gen")),
			Internal: pathFromWorkingDir(filepath.Join(resolvedRoot, "internal")),
			Legacy:   versioningCompatibilityMode(m),
		})
		if err != nil {
			return fmt.Errorf("version generate: %w", err)
		}
		err = generator.GeneratePostgresMigrationAt(resolvedRoot, m)
		if err != nil {
			return fmt.Errorf("postgres migration generation: %w", err)
		}
	}
	if !o.skipSQLC && !o.wireOnly {
		if fileExists(filepath.Join(resolvedRoot, "sqlc.yaml")) {
			err = runCommandDir(ctx, resolvedRoot, "sqlc", "generate")
			if err != nil {
				return fmt.Errorf("sqlc generate: %w", err)
			}
		}
	}
	if !o.skipCQL && !o.wireOnly {
		if fileExists(filepath.Join(resolvedRoot, "cql")) || fileExists(filepath.Join(resolvedRoot, "cqlc.yaml")) {
			err = cqlgen.Generate(resolvedRoot, filepath.Join(resolvedRoot, "gen", "cql"))
			if err != nil {
				return fmt.Errorf("cql generate: %w", err)
			}
		}
	}
	return nil
}

// versioningCompatibilityMode converts manifest compatibility settings into generator mode.
func versioningCompatibilityMode(m *manifest.Manifest) versioning.CompatibilityMode {
	if m == nil || !m.LegacyCompatibilityConfigured() {
		return versioning.CompatibilityAuto
	}
	if m.LegacyCompatibilityEnabled() {
		return versioning.CompatibilityEnabled
	}
	return versioning.CompatibilityDisabled
}

// runGenerateMainOptsIn renders generated main and auxiliary docs under the service root.
func runGenerateMainOptsIn(rootDir, manifestPath string, o genOptions) error {
	paths, err := resolveServicePaths(rootDir, manifestPath)
	if err != nil {
		return err
	}
	var m *manifest.Manifest
	m, err = manifest.Load(paths.manifestPath)
	if err != nil {
		return fmt.Errorf("manifest load: %w", err)
	}
	if !o.skipMain {
		mainPath := filepath.Join(paths.rootDir, "cmd", "main.go")
		trackMain := shouldTrackGeneratedMain(mainPath)
		if fileExists(mainPath) && !o.forceMain && !trackMain {
			if !o.quietMain {
				fmt.Println("skip main generation: cmd/main.go already exists")
			}
		} else {
			err := generator.GenerateMain(m, mainPath)
			if err != nil {
				return fmt.Errorf("main generation: %w", err)
			}
		}
	}
	err = generator.GenerateCursorRulesAt(paths.rootDir, m.Service.Name)
	if err != nil {
		return fmt.Errorf("cursor rules generation: %w", err)
	}
	err = generator.GenerateBufRegistryDocAt(paths.rootDir, m.Service.Name)
	if err != nil {
		return fmt.Errorf("proto registry doc generation: %w", err)
	}
	return nil
}

// finalizeInit performs the post-scaffold dependency and generation steps for zengo init.
func finalizeInit(ctx context.Context, dir string) error {
	paths, err := resolveServicePaths(dir, "")
	if err != nil {
		return err
	}
	err = runCommandDir(ctx, paths.rootDir, "buf", "dep", "update")
	if err != nil {
		return fmt.Errorf("buf dep update: %w", err)
	}
	return runGenerateAll(paths.rootDir, paths.manifestPath, genOptions{ctx: ctx, quietMain: true, forceMain: true})
}

type generatedPlan struct {
	targets      []string
	forceMain    bool
	rootDir      string
	manifestPath string
}

type generatedSnapshot struct {
	displayPath string
	path        string
	backupPath  string
	exists      bool
	isDir       bool
}

var staticGeneratedTargets = []string{
	"gen/api",
	"gen/zengo",
	"gen/db",
	"gen/cql",
	filepath.Join(".cursor", "rules"),
	filepath.Join("docs", "PROTO_REGISTRY.md"),
}

func checkGenFreshIn(ctx context.Context, rootDir, manifestPath string, skipBuf bool) (retErr error) {
	plan, err := generatedTargetsIn(rootDir, manifestPath)
	if err != nil {
		return err
	}
	var bakRoot string

	bakRoot, err = os.MkdirTemp("", "zengo-check-gen-*")
	if err != nil {
		return err
	}
	defer func() {
		retErr = errors.Join(retErr, os.RemoveAll(bakRoot))
	}()
	var snapshots []generatedSnapshot

	snapshots, err = snapshotGeneratedTargetsIn(plan.rootDir, plan.targets, bakRoot)
	if err != nil {
		return err
	}

	genErr := runGenerateAll(
		plan.rootDir,
		plan.manifestPath,
		genOptions{ctx: ctx, skipBuf: skipBuf, quietMain: true, forceMain: plan.forceMain},
	)
	if genErr == nil && !skipBuf {
		genErr = runGenerateAll(
			plan.rootDir,
			plan.manifestPath,
			genOptions{ctx: ctx, skipBuf: true, quietMain: true, forceMain: plan.forceMain},
		)
	}

	stale, diffErr := diffGeneratedTargets(snapshots)
	restoreErr := restoreGeneratedTargets(snapshots)
	if genErr != nil {
		if restoreErr != nil {
			return errors.Join(genErr, fmt.Errorf("restore generated targets: %w", restoreErr))
		}
		return genErr
	}
	if diffErr != nil {
		if restoreErr != nil {
			return errors.Join(diffErr, fmt.Errorf("restore generated targets: %w", restoreErr))
		}
		return diffErr
	}
	if restoreErr != nil {
		return restoreErr
	}
	if len(stale) > 0 {
		return fmt.Errorf("generated code is stale (%s); run: zengo gen", strings.Join(stale, ", "))
	}
	return nil
}

func generatedTargets(manifestPath string) (generatedPlan, error) {
	return generatedTargetsIn(".", manifestPath)
}

func generatedTargetsIn(rootDir, manifestPath string) (generatedPlan, error) {
	paths, err := resolveServicePaths(rootDir, manifestPath)
	if err != nil {
		return generatedPlan{}, err
	}
	plan := generatedPlan{
		targets:      append([]string(nil), staticGeneratedTargets...),
		rootDir:      paths.rootDir,
		manifestPath: paths.manifestPath,
	}
	mainPath := filepath.Join(paths.rootDir, "cmd", "main.go")
	plan.forceMain = shouldTrackGeneratedMain(mainPath)
	if plan.forceMain {
		plan.targets = append(plan.targets, filepath.Join("cmd", "main.go"))
	}
	var m *manifest.Manifest
	m, err = manifest.Load(paths.manifestPath)
	if err != nil {
		return generatedPlan{}, fmt.Errorf("manifest load: %w", err)
	}
	if m.Transports.REST != nil {
		plan.targets = append(plan.targets, filepath.Join("gen", "openapi"))
	}
	trackMigration, err := generator.ShouldTrackPostgresMigrationAt(paths.rootDir, m)
	if err != nil {
		return generatedPlan{}, fmt.Errorf("postgres migration tracking: %w", err)
	}
	if trackMigration {
		plan.targets = append(plan.targets, filepath.Join("migrations", "001_init.sql"))
	}
	return plan, nil
}

func shouldTrackGeneratedMain(path string) bool {
	data, err := os.ReadFile(path)
	if os.IsNotExist(err) {
		return true
	}
	if err != nil {
		return false
	}
	return strings.HasPrefix(string(data), generatedMainHeader)
}

func snapshotGeneratedTargets(targets []string, bakRoot string) ([]generatedSnapshot, error) {
	return snapshotGeneratedTargetsIn(".", targets, bakRoot)
}

func snapshotGeneratedTargetsIn(rootDir string, targets []string, bakRoot string) ([]generatedSnapshot, error) {
	snapshots := make([]generatedSnapshot, 0, len(targets))
	for i, displayPath := range targets {
		path := filepath.Join(rootDir, displayPath)
		snapshot := generatedSnapshot{
			displayPath: displayPath,
			path:        path,
			backupPath:  filepath.Join(bakRoot, fmt.Sprintf("%03d", i)),
		}
		info, err := os.Stat(path)
		if err != nil {
			if os.IsNotExist(err) {
				snapshots = append(snapshots, snapshot)
				continue
			}
			return nil, err
		}
		snapshot.exists = true
		snapshot.isDir = info.IsDir()
		if snapshot.isDir {
			err = copyDir(path, snapshot.backupPath)
			if err != nil {
				return nil, err
			}
		} else {
			var data []byte
			data, err = os.ReadFile(path)
			if err != nil {
				return nil, err
			}
			err = writeFile(snapshot.backupPath, data)
			if err != nil {
				return nil, err
			}
		}
		snapshots = append(snapshots, snapshot)
	}
	return snapshots, nil
}

func diffGeneratedTargets(snapshots []generatedSnapshot) ([]string, error) {
	var stale []string
	for _, snapshot := range snapshots {
		dirty, err := snapshotChanged(snapshot)
		if err != nil {
			return nil, err
		}
		if dirty {
			stale = append(stale, snapshot.displayPath)
		}
	}
	return stale, nil
}

func snapshotChanged(snapshot generatedSnapshot) (bool, error) {
	info, err := os.Stat(snapshot.path)
	if !snapshot.exists {
		if os.IsNotExist(err) {
			return false, nil
		}
		if err != nil {
			return false, err
		}
		return true, nil
	}
	if err != nil {
		if os.IsNotExist(err) {
			return true, nil
		}
		return false, err
	}
	if info.IsDir() != snapshot.isDir {
		return true, nil
	}
	if snapshot.isDir {
		return compareDirTrees(snapshot.path, snapshot.backupPath)
	}
	var a []byte

	a, err = os.ReadFile(snapshot.path)
	if err != nil {
		return false, err
	}
	var b []byte

	b, err = os.ReadFile(snapshot.backupPath)
	if err != nil {
		return false, err
	}
	return !bytes.Equal(a, b), nil
}

func restoreGeneratedTargets(snapshots []generatedSnapshot) error {
	for _, snapshot := range snapshots {
		if !snapshot.exists {
			err := os.RemoveAll(snapshot.path)
			if err != nil && !os.IsNotExist(err) {
				return err
			}
			continue
		}
		err := os.RemoveAll(snapshot.path)
		if err != nil && !os.IsNotExist(err) {
			return err
		}
		if snapshot.isDir {
			err = copyDir(snapshot.backupPath, snapshot.path)
			if err != nil {
				return err
			}
			continue
		}
		var data []byte

		data, err = os.ReadFile(snapshot.backupPath)
		if err != nil {
			return err
		}
		err = writeFile(snapshot.path, data)
		if err != nil {
			return err
		}
	}
	return nil
}

func copyDir(src, dst string) error {
	return filepath.WalkDir(src, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		var rel string

		rel, err = filepath.Rel(src, path)
		if err != nil {
			return err
		}
		target := filepath.Join(dst, rel)
		if d.IsDir() {
			return os.MkdirAll(target, 0o755)
		}
		var data []byte

		data, err = os.ReadFile(path)
		if err != nil {
			return err
		}
		return writeFile(target, data)
	})
}

func compareDirTrees(src, dst string) (bool, error) {
	a, err := treeEntries(src)
	if err != nil {
		return false, err
	}
	var b map[string]treeEntry

	b, err = treeEntries(dst)
	if err != nil {
		return false, err
	}
	if len(a) != len(b) {
		return true, nil
	}
	for rel, left := range a {
		right, ok := b[rel]
		if !ok {
			return true, nil
		}
		if left.dir != right.dir {
			return true, nil
		}
		if !left.dir && !bytes.Equal(left.data, right.data) {
			return true, nil
		}
	}
	return false, nil
}

type treeEntry struct {
	dir  bool
	data []byte
}

func treeEntries(root string) (map[string]treeEntry, error) {
	entries := map[string]treeEntry{}
	err := filepath.WalkDir(root, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		var rel string

		rel, err = filepath.Rel(root, path)
		if err != nil {
			return err
		}
		if d.IsDir() {
			entries[rel] = treeEntry{dir: true}
			return nil
		}
		var data []byte

		data, err = os.ReadFile(path)
		if err != nil {
			return err
		}
		entries[rel] = treeEntry{data: data}
		return nil
	})
	if err != nil {
		return nil, err
	}
	return entries, nil
}

func writeFile(path string, data []byte) error {
	err := os.MkdirAll(filepath.Dir(path), 0o755)
	if err != nil {
		return err
	}
	return os.WriteFile(path, data, 0o644)
}

func pathFromWorkingDir(path string) string {
	wd, err := os.Getwd()
	if err != nil {
		return path
	}
	var rel string

	rel, err = filepath.Rel(wd, path)
	if err != nil {
		return path
	}
	return rel
}
