// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: config/queue/kafka/config.proto

package kafka

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
	meta "zengo/platform/api/config/meta"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Kafka config document.
//
// Config is the typed Kafka configuration loaded by the platform runtime.
type Config struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Config kind.
	//
	// kind is the logical config kind used by the loader.
	Kind string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	// Config API version.
	//
	// api_version identifies the document version used for compatibility over time.
	ApiVersion string `protobuf:"bytes,2,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	// Kafka settings.
	//
	// spec contains the Kafka client settings consumed by the runtime.
	Spec          *Spec `protobuf:"bytes,3,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_config_queue_kafka_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_config_queue_kafka_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_config_queue_kafka_config_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Config) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *Config) GetSpec() *Spec {
	if x != nil {
		return x.Spec
	}
	return nil
}

// Kafka settings.
//
// Spec configures Kafka broker connectivity and client identity.
type Spec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Broker list.
	//
	// brokers lists Kafka brokers used by producers and consumers.
	Brokers []string `protobuf:"bytes,1,rep,name=brokers,proto3" json:"brokers,omitempty"`
	// Client identifier.
	//
	// client_id is the optional Kafka client identifier.
	ClientId string `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// Consumer group.
	//
	// group_id is the optional default consumer group identifier.
	GroupId *string `protobuf:"bytes,3,opt,name=group_id,json=groupId,proto3,oneof" json:"group_id,omitempty"`
	// TLS settings.
	//
	// tls configures TLS and optional mTLS for Kafka broker connections.
	Tls           *meta.ClientTLS `protobuf:"bytes,4,opt,name=tls,proto3" json:"tls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Spec) Reset() {
	*x = Spec{}
	mi := &file_config_queue_kafka_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Spec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Spec) ProtoMessage() {}

func (x *Spec) ProtoReflect() protoreflect.Message {
	mi := &file_config_queue_kafka_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Spec.ProtoReflect.Descriptor instead.
func (*Spec) Descriptor() ([]byte, []int) {
	return file_config_queue_kafka_config_proto_rawDescGZIP(), []int{1}
}

func (x *Spec) GetBrokers() []string {
	if x != nil {
		return x.Brokers
	}
	return nil
}

func (x *Spec) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *Spec) GetGroupId() string {
	if x != nil && x.GroupId != nil {
		return *x.GroupId
	}
	return ""
}

func (x *Spec) GetTls() *meta.ClientTLS {
	if x != nil {
		return x.Tls
	}
	return nil
}

var File_config_queue_kafka_config_proto protoreflect.FileDescriptor

const file_config_queue_kafka_config_proto_rawDesc = "" +
	"\n" +
	"\x1fconfig/queue/kafka/config.proto\x12\x12zengo.config.kafka\x1a\x15config/meta/tls.proto\"k\n" +
	"\x06Config\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x1f\n" +
	"\vapi_version\x18\x02 \x01(\tR\n" +
	"apiVersion\x12,\n" +
	"\x04spec\x18\x03 \x01(\v2\x18.zengo.config.kafka.SpecR\x04spec\"\x9a\x01\n" +
	"\x04Spec\x12\x18\n" +
	"\abrokers\x18\x01 \x03(\tR\abrokers\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12\x1e\n" +
	"\bgroup_id\x18\x03 \x01(\tH\x00R\agroupId\x88\x01\x01\x12.\n" +
	"\x03tls\x18\x04 \x01(\v2\x1c.zengo.config.meta.ClientTLSR\x03tlsB\v\n" +
	"\t_group_idB'Z%zengo/platform/api/config/queue/kafkab\x06proto3"

var (
	file_config_queue_kafka_config_proto_rawDescOnce sync.Once
	file_config_queue_kafka_config_proto_rawDescData []byte
)

func file_config_queue_kafka_config_proto_rawDescGZIP() []byte {
	file_config_queue_kafka_config_proto_rawDescOnce.Do(func() {
		file_config_queue_kafka_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_config_queue_kafka_config_proto_rawDesc), len(file_config_queue_kafka_config_proto_rawDesc)))
	})
	return file_config_queue_kafka_config_proto_rawDescData
}

var file_config_queue_kafka_config_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_config_queue_kafka_config_proto_goTypes = []any{
	(*Config)(nil),         // 0: zengo.config.kafka.Config
	(*Spec)(nil),           // 1: zengo.config.kafka.Spec
	(*meta.ClientTLS)(nil), // 2: zengo.config.meta.ClientTLS
}
var file_config_queue_kafka_config_proto_depIdxs = []int32{
	1, // 0: zengo.config.kafka.Config.spec:type_name -> zengo.config.kafka.Spec
	2, // 1: zengo.config.kafka.Spec.tls:type_name -> zengo.config.meta.ClientTLS
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_config_queue_kafka_config_proto_init() }
func file_config_queue_kafka_config_proto_init() {
	if File_config_queue_kafka_config_proto != nil {
		return
	}
	file_config_queue_kafka_config_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_config_queue_kafka_config_proto_rawDesc), len(file_config_queue_kafka_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_config_queue_kafka_config_proto_goTypes,
		DependencyIndexes: file_config_queue_kafka_config_proto_depIdxs,
		MessageInfos:      file_config_queue_kafka_config_proto_msgTypes,
	}.Build()
	File_config_queue_kafka_config_proto = out.File
	file_config_queue_kafka_config_proto_goTypes = nil
	file_config_queue_kafka_config_proto_depIdxs = nil
}
