// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: config/storage/s3/config.proto

package s3

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
	meta "zengo/platform/api/config/meta"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// S3 config document.
//
// Config is the typed S3-compatible storage configuration loaded by the platform runtime.
type Config struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Config kind.
	//
	// kind is the logical config kind used by the loader.
	Kind string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	// Config API version.
	//
	// api_version identifies the document version used for compatibility over time.
	ApiVersion string `protobuf:"bytes,2,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	// S3 settings.
	//
	// spec contains the S3 client settings consumed by the runtime.
	Spec          *Spec `protobuf:"bytes,3,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_config_storage_s3_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_config_storage_s3_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_config_storage_s3_config_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Config) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *Config) GetSpec() *Spec {
	if x != nil {
		return x.Spec
	}
	return nil
}

// S3 settings.
//
// Spec configures S3-compatible object storage access.
type Spec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Default bucket.
	//
	// bucket is the default bucket used by helpers when operations do not override it.
	Bucket *string `protobuf:"bytes,1,opt,name=bucket,proto3,oneof" json:"bucket,omitempty"`
	// AWS region.
	//
	// region is the AWS region passed to the SDK.
	Region *string `protobuf:"bytes,2,opt,name=region,proto3,oneof" json:"region,omitempty"`
	// Custom endpoint.
	//
	// endpoint overrides the default AWS endpoint, for example for MinIO.
	Endpoint *string `protobuf:"bytes,3,opt,name=endpoint,proto3,oneof" json:"endpoint,omitempty"`
	// Access key ID.
	//
	// access_key_id is the optional static access key for the SDK.
	AccessKeyId *string `protobuf:"bytes,4,opt,name=access_key_id,json=accessKeyId,proto3,oneof" json:"access_key_id,omitempty"`
	// Secret access key.
	//
	// secret_access_key is the optional static secret key for the SDK.
	SecretAccessKey *string `protobuf:"bytes,5,opt,name=secret_access_key,json=secretAccessKey,proto3,oneof" json:"secret_access_key,omitempty"`
	// Session token.
	//
	// session_token is the optional static session token for the SDK.
	SessionToken *string `protobuf:"bytes,6,opt,name=session_token,json=sessionToken,proto3,oneof" json:"session_token,omitempty"`
	// Path-style flag.
	//
	// force_path_style is required for MinIO and some on-prem S3-compatible stores.
	ForcePathStyle *bool `protobuf:"varint,7,opt,name=force_path_style,json=forcePathStyle,proto3,oneof" json:"force_path_style,omitempty"`
	// TLS settings.
	//
	// tls configures TLS and optional mTLS when the endpoint supports it.
	Tls *meta.ClientTLS `protobuf:"bytes,8,opt,name=tls,proto3" json:"tls,omitempty"`
	// Object key prefix.
	//
	// prefix is the default object key prefix used by helpers.
	Prefix *string `protobuf:"bytes,9,opt,name=prefix,proto3,oneof" json:"prefix,omitempty"`
	// Request timeout.
	//
	// request_timeout bounds SDK HTTP requests.
	RequestTimeout *durationpb.Duration `protobuf:"bytes,10,opt,name=request_timeout,json=requestTimeout,proto3,oneof" json:"request_timeout,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Spec) Reset() {
	*x = Spec{}
	mi := &file_config_storage_s3_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Spec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Spec) ProtoMessage() {}

func (x *Spec) ProtoReflect() protoreflect.Message {
	mi := &file_config_storage_s3_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Spec.ProtoReflect.Descriptor instead.
func (*Spec) Descriptor() ([]byte, []int) {
	return file_config_storage_s3_config_proto_rawDescGZIP(), []int{1}
}

func (x *Spec) GetBucket() string {
	if x != nil && x.Bucket != nil {
		return *x.Bucket
	}
	return ""
}

func (x *Spec) GetRegion() string {
	if x != nil && x.Region != nil {
		return *x.Region
	}
	return ""
}

func (x *Spec) GetEndpoint() string {
	if x != nil && x.Endpoint != nil {
		return *x.Endpoint
	}
	return ""
}

func (x *Spec) GetAccessKeyId() string {
	if x != nil && x.AccessKeyId != nil {
		return *x.AccessKeyId
	}
	return ""
}

func (x *Spec) GetSecretAccessKey() string {
	if x != nil && x.SecretAccessKey != nil {
		return *x.SecretAccessKey
	}
	return ""
}

func (x *Spec) GetSessionToken() string {
	if x != nil && x.SessionToken != nil {
		return *x.SessionToken
	}
	return ""
}

func (x *Spec) GetForcePathStyle() bool {
	if x != nil && x.ForcePathStyle != nil {
		return *x.ForcePathStyle
	}
	return false
}

func (x *Spec) GetTls() *meta.ClientTLS {
	if x != nil {
		return x.Tls
	}
	return nil
}

func (x *Spec) GetPrefix() string {
	if x != nil && x.Prefix != nil {
		return *x.Prefix
	}
	return ""
}

func (x *Spec) GetRequestTimeout() *durationpb.Duration {
	if x != nil {
		return x.RequestTimeout
	}
	return nil
}

var File_config_storage_s3_config_proto protoreflect.FileDescriptor

const file_config_storage_s3_config_proto_rawDesc = "" +
	"\n" +
	"\x1econfig/storage/s3/config.proto\x12\x0fzengo.config.s3\x1a\x15config/meta/tls.proto\x1a\x1egoogle/protobuf/duration.proto\"h\n" +
	"\x06Config\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x1f\n" +
	"\vapi_version\x18\x02 \x01(\tR\n" +
	"apiVersion\x12)\n" +
	"\x04spec\x18\x03 \x01(\v2\x15.zengo.config.s3.SpecR\x04spec\"\xbb\x04\n" +
	"\x04Spec\x12\x1b\n" +
	"\x06bucket\x18\x01 \x01(\tH\x00R\x06bucket\x88\x01\x01\x12\x1b\n" +
	"\x06region\x18\x02 \x01(\tH\x01R\x06region\x88\x01\x01\x12\x1f\n" +
	"\bendpoint\x18\x03 \x01(\tH\x02R\bendpoint\x88\x01\x01\x12'\n" +
	"\raccess_key_id\x18\x04 \x01(\tH\x03R\vaccessKeyId\x88\x01\x01\x12/\n" +
	"\x11secret_access_key\x18\x05 \x01(\tH\x04R\x0fsecretAccessKey\x88\x01\x01\x12(\n" +
	"\rsession_token\x18\x06 \x01(\tH\x05R\fsessionToken\x88\x01\x01\x12-\n" +
	"\x10force_path_style\x18\a \x01(\bH\x06R\x0eforcePathStyle\x88\x01\x01\x12.\n" +
	"\x03tls\x18\b \x01(\v2\x1c.zengo.config.meta.ClientTLSR\x03tls\x12\x1b\n" +
	"\x06prefix\x18\t \x01(\tH\aR\x06prefix\x88\x01\x01\x12G\n" +
	"\x0frequest_timeout\x18\n" +
	" \x01(\v2\x19.google.protobuf.DurationH\bR\x0erequestTimeout\x88\x01\x01B\t\n" +
	"\a_bucketB\t\n" +
	"\a_regionB\v\n" +
	"\t_endpointB\x10\n" +
	"\x0e_access_key_idB\x14\n" +
	"\x12_secret_access_keyB\x10\n" +
	"\x0e_session_tokenB\x13\n" +
	"\x11_force_path_styleB\t\n" +
	"\a_prefixB\x12\n" +
	"\x10_request_timeoutB&Z$zengo/platform/api/config/storage/s3b\x06proto3"

var (
	file_config_storage_s3_config_proto_rawDescOnce sync.Once
	file_config_storage_s3_config_proto_rawDescData []byte
)

func file_config_storage_s3_config_proto_rawDescGZIP() []byte {
	file_config_storage_s3_config_proto_rawDescOnce.Do(func() {
		file_config_storage_s3_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_config_storage_s3_config_proto_rawDesc), len(file_config_storage_s3_config_proto_rawDesc)))
	})
	return file_config_storage_s3_config_proto_rawDescData
}

var file_config_storage_s3_config_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_config_storage_s3_config_proto_goTypes = []any{
	(*Config)(nil),              // 0: zengo.config.s3.Config
	(*Spec)(nil),                // 1: zengo.config.s3.Spec
	(*meta.ClientTLS)(nil),      // 2: zengo.config.meta.ClientTLS
	(*durationpb.Duration)(nil), // 3: google.protobuf.Duration
}
var file_config_storage_s3_config_proto_depIdxs = []int32{
	1, // 0: zengo.config.s3.Config.spec:type_name -> zengo.config.s3.Spec
	2, // 1: zengo.config.s3.Spec.tls:type_name -> zengo.config.meta.ClientTLS
	3, // 2: zengo.config.s3.Spec.request_timeout:type_name -> google.protobuf.Duration
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_config_storage_s3_config_proto_init() }
func file_config_storage_s3_config_proto_init() {
	if File_config_storage_s3_config_proto != nil {
		return
	}
	file_config_storage_s3_config_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_config_storage_s3_config_proto_rawDesc), len(file_config_storage_s3_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_config_storage_s3_config_proto_goTypes,
		DependencyIndexes: file_config_storage_s3_config_proto_depIdxs,
		MessageInfos:      file_config_storage_s3_config_proto_msgTypes,
	}.Build()
	File_config_storage_s3_config_proto = out.File
	file_config_storage_s3_config_proto_goTypes = nil
	file_config_storage_s3_config_proto_depIdxs = nil
}
