// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: config/meta/type.proto

package meta

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Shared config metadata.
//
// Type contains the metadata fields shared by typed config documents.
type Type struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Config kind.
	//
	// kind is the logical config kind used by the loader, for example "postgres".
	Kind string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	// Config API version.
	//
	// api_version identifies the document version used for compatibility over time.
	ApiVersion    *string `protobuf:"bytes,2,opt,name=api_version,json=apiVersion,proto3,oneof" json:"api_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Type) Reset() {
	*x = Type{}
	mi := &file_config_meta_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Type) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Type) ProtoMessage() {}

func (x *Type) ProtoReflect() protoreflect.Message {
	mi := &file_config_meta_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Type.ProtoReflect.Descriptor instead.
func (*Type) Descriptor() ([]byte, []int) {
	return file_config_meta_type_proto_rawDescGZIP(), []int{0}
}

func (x *Type) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Type) GetApiVersion() string {
	if x != nil && x.ApiVersion != nil {
		return *x.ApiVersion
	}
	return ""
}

var File_config_meta_type_proto protoreflect.FileDescriptor

const file_config_meta_type_proto_rawDesc = "" +
	"\n" +
	"\x16config/meta/type.proto\x12\x11zengo.config.meta\"P\n" +
	"\x04Type\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12$\n" +
	"\vapi_version\x18\x02 \x01(\tH\x00R\n" +
	"apiVersion\x88\x01\x01B\x0e\n" +
	"\f_api_versionB Z\x1ezengo/platform/api/config/metab\x06proto3"

var (
	file_config_meta_type_proto_rawDescOnce sync.Once
	file_config_meta_type_proto_rawDescData []byte
)

func file_config_meta_type_proto_rawDescGZIP() []byte {
	file_config_meta_type_proto_rawDescOnce.Do(func() {
		file_config_meta_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_config_meta_type_proto_rawDesc), len(file_config_meta_type_proto_rawDesc)))
	})
	return file_config_meta_type_proto_rawDescData
}

var file_config_meta_type_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_config_meta_type_proto_goTypes = []any{
	(*Type)(nil), // 0: zengo.config.meta.Type
}
var file_config_meta_type_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_config_meta_type_proto_init() }
func file_config_meta_type_proto_init() {
	if File_config_meta_type_proto != nil {
		return
	}
	file_config_meta_type_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_config_meta_type_proto_rawDesc), len(file_config_meta_type_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_config_meta_type_proto_goTypes,
		DependencyIndexes: file_config_meta_type_proto_depIdxs,
		MessageInfos:      file_config_meta_type_proto_msgTypes,
	}.Build()
	File_config_meta_type_proto = out.File
	file_config_meta_type_proto_goTypes = nil
	file_config_meta_type_proto_depIdxs = nil
}
