// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: config/meta/tls.proto

package meta

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Client auth mode.
//
// ClientAuth controls whether the server requests or requires client certificates.
type ServerTLS_ClientAuth int32

const (
	ServerTLS_NONE               ServerTLS_ClientAuth = 0
	ServerTLS_VERIFY_IF_GIVEN    ServerTLS_ClientAuth = 1
	ServerTLS_REQUIRE_AND_VERIFY ServerTLS_ClientAuth = 2
)

// Enum value maps for ServerTLS_ClientAuth.
var (
	ServerTLS_ClientAuth_name = map[int32]string{
		0: "NONE",
		1: "VERIFY_IF_GIVEN",
		2: "REQUIRE_AND_VERIFY",
	}
	ServerTLS_ClientAuth_value = map[string]int32{
		"NONE":               0,
		"VERIFY_IF_GIVEN":    1,
		"REQUIRE_AND_VERIFY": 2,
	}
)

func (x ServerTLS_ClientAuth) Enum() *ServerTLS_ClientAuth {
	p := new(ServerTLS_ClientAuth)
	*p = x
	return p
}

func (x ServerTLS_ClientAuth) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServerTLS_ClientAuth) Descriptor() protoreflect.EnumDescriptor {
	return file_config_meta_tls_proto_enumTypes[0].Descriptor()
}

func (ServerTLS_ClientAuth) Type() protoreflect.EnumType {
	return &file_config_meta_tls_proto_enumTypes[0]
}

func (x ServerTLS_ClientAuth) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServerTLS_ClientAuth.Descriptor instead.
func (ServerTLS_ClientAuth) EnumDescriptor() ([]byte, []int) {
	return file_config_meta_tls_proto_rawDescGZIP(), []int{2, 0}
}

// TLS material source.
//
// TLSMaterial identifies a TLS artifact either by filesystem path or by inline PEM content.
type TLSMaterial struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Source:
	//
	//	*TLSMaterial_Path
	//	*TLSMaterial_InlinePem
	Source        isTLSMaterial_Source `protobuf_oneof:"source"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TLSMaterial) Reset() {
	*x = TLSMaterial{}
	mi := &file_config_meta_tls_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TLSMaterial) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLSMaterial) ProtoMessage() {}

func (x *TLSMaterial) ProtoReflect() protoreflect.Message {
	mi := &file_config_meta_tls_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLSMaterial.ProtoReflect.Descriptor instead.
func (*TLSMaterial) Descriptor() ([]byte, []int) {
	return file_config_meta_tls_proto_rawDescGZIP(), []int{0}
}

func (x *TLSMaterial) GetSource() isTLSMaterial_Source {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *TLSMaterial) GetPath() string {
	if x != nil {
		if x, ok := x.Source.(*TLSMaterial_Path); ok {
			return x.Path
		}
	}
	return ""
}

func (x *TLSMaterial) GetInlinePem() string {
	if x != nil {
		if x, ok := x.Source.(*TLSMaterial_InlinePem); ok {
			return x.InlinePem
		}
	}
	return ""
}

type isTLSMaterial_Source interface {
	isTLSMaterial_Source()
}

type TLSMaterial_Path struct {
	// PEM file path.
	//
	// path points to a PEM file on disk.
	Path string `protobuf:"bytes,1,opt,name=path,proto3,oneof"`
}

type TLSMaterial_InlinePem struct {
	// Inline PEM data.
	//
	// inline_pem stores PEM content directly inside the config document.
	InlinePem string `protobuf:"bytes,2,opt,name=inline_pem,json=inlinePem,proto3,oneof"`
}

func (*TLSMaterial_Path) isTLSMaterial_Source() {}

func (*TLSMaterial_InlinePem) isTLSMaterial_Source() {}

// Client TLS settings.
//
// ClientTLS configures client-side TLS and optional mTLS for outgoing connections.
type ClientTLS struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Trusted CA bundle.
	//
	// ca supplies the CA certificates used to verify the remote server.
	Ca *TLSMaterial `protobuf:"bytes,1,opt,name=ca,proto3" json:"ca,omitempty"`
	// Client certificate.
	//
	// cert supplies the client certificate for mTLS when the upstream requires it.
	Cert *TLSMaterial `protobuf:"bytes,2,opt,name=cert,proto3" json:"cert,omitempty"`
	// Client private key.
	//
	// key supplies the private key that matches cert.
	Key *TLSMaterial `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	// TLS server name.
	//
	// server_name overrides the expected server name used during certificate verification.
	ServerName string `protobuf:"bytes,4,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	// Skip verification flag.
	//
	// insecure_skip_verify disables remote certificate verification.
	InsecureSkipVerify bool `protobuf:"varint,5,opt,name=insecure_skip_verify,json=insecureSkipVerify,proto3" json:"insecure_skip_verify,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ClientTLS) Reset() {
	*x = ClientTLS{}
	mi := &file_config_meta_tls_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientTLS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientTLS) ProtoMessage() {}

func (x *ClientTLS) ProtoReflect() protoreflect.Message {
	mi := &file_config_meta_tls_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientTLS.ProtoReflect.Descriptor instead.
func (*ClientTLS) Descriptor() ([]byte, []int) {
	return file_config_meta_tls_proto_rawDescGZIP(), []int{1}
}

func (x *ClientTLS) GetCa() *TLSMaterial {
	if x != nil {
		return x.Ca
	}
	return nil
}

func (x *ClientTLS) GetCert() *TLSMaterial {
	if x != nil {
		return x.Cert
	}
	return nil
}

func (x *ClientTLS) GetKey() *TLSMaterial {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *ClientTLS) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *ClientTLS) GetInsecureSkipVerify() bool {
	if x != nil {
		return x.InsecureSkipVerify
	}
	return false
}

// Server TLS settings.
//
// ServerTLS configures server-side TLS and optional client-certificate verification.
type ServerTLS struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Server certificate.
	//
	// cert supplies the leaf server certificate presented to clients.
	Cert *TLSMaterial `protobuf:"bytes,1,opt,name=cert,proto3" json:"cert,omitempty"`
	// Server private key.
	//
	// key supplies the private key that matches cert.
	Key *TLSMaterial `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	// Certificate chain bundle.
	//
	// ca optionally appends additional PEM certificates to the served chain.
	Ca *TLSMaterial `protobuf:"bytes,3,opt,name=ca,proto3" json:"ca,omitempty"`
	// Trusted client CA bundle.
	//
	// client_ca supplies the CA certificates used to verify client certificates during mTLS.
	ClientCa *TLSMaterial `protobuf:"bytes,4,opt,name=client_ca,json=clientCa,proto3" json:"client_ca,omitempty"`
	// TLS server name.
	//
	// server_name is reserved for environments that need an explicit logical TLS name.
	ServerName string `protobuf:"bytes,5,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	// Client auth policy.
	//
	// client_auth selects whether client certificates are optional, verified when present, or required.
	ClientAuth    ServerTLS_ClientAuth `protobuf:"varint,6,opt,name=client_auth,json=clientAuth,proto3,enum=zengo.config.meta.ServerTLS_ClientAuth" json:"client_auth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerTLS) Reset() {
	*x = ServerTLS{}
	mi := &file_config_meta_tls_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerTLS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerTLS) ProtoMessage() {}

func (x *ServerTLS) ProtoReflect() protoreflect.Message {
	mi := &file_config_meta_tls_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerTLS.ProtoReflect.Descriptor instead.
func (*ServerTLS) Descriptor() ([]byte, []int) {
	return file_config_meta_tls_proto_rawDescGZIP(), []int{2}
}

func (x *ServerTLS) GetCert() *TLSMaterial {
	if x != nil {
		return x.Cert
	}
	return nil
}

func (x *ServerTLS) GetKey() *TLSMaterial {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *ServerTLS) GetCa() *TLSMaterial {
	if x != nil {
		return x.Ca
	}
	return nil
}

func (x *ServerTLS) GetClientCa() *TLSMaterial {
	if x != nil {
		return x.ClientCa
	}
	return nil
}

func (x *ServerTLS) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *ServerTLS) GetClientAuth() ServerTLS_ClientAuth {
	if x != nil {
		return x.ClientAuth
	}
	return ServerTLS_NONE
}

var File_config_meta_tls_proto protoreflect.FileDescriptor

const file_config_meta_tls_proto_rawDesc = "" +
	"\n" +
	"\x15config/meta/tls.proto\x12\x11zengo.config.meta\"N\n" +
	"\vTLSMaterial\x12\x14\n" +
	"\x04path\x18\x01 \x01(\tH\x00R\x04path\x12\x1f\n" +
	"\n" +
	"inline_pem\x18\x02 \x01(\tH\x00R\tinlinePemB\b\n" +
	"\x06source\"\xf4\x01\n" +
	"\tClientTLS\x12.\n" +
	"\x02ca\x18\x01 \x01(\v2\x1e.zengo.config.meta.TLSMaterialR\x02ca\x122\n" +
	"\x04cert\x18\x02 \x01(\v2\x1e.zengo.config.meta.TLSMaterialR\x04cert\x120\n" +
	"\x03key\x18\x03 \x01(\v2\x1e.zengo.config.meta.TLSMaterialR\x03key\x12\x1f\n" +
	"\vserver_name\x18\x04 \x01(\tR\n" +
	"serverName\x120\n" +
	"\x14insecure_skip_verify\x18\x05 \x01(\bR\x12insecureSkipVerify\"\x8e\x03\n" +
	"\tServerTLS\x122\n" +
	"\x04cert\x18\x01 \x01(\v2\x1e.zengo.config.meta.TLSMaterialR\x04cert\x120\n" +
	"\x03key\x18\x02 \x01(\v2\x1e.zengo.config.meta.TLSMaterialR\x03key\x12.\n" +
	"\x02ca\x18\x03 \x01(\v2\x1e.zengo.config.meta.TLSMaterialR\x02ca\x12;\n" +
	"\tclient_ca\x18\x04 \x01(\v2\x1e.zengo.config.meta.TLSMaterialR\bclientCa\x12\x1f\n" +
	"\vserver_name\x18\x05 \x01(\tR\n" +
	"serverName\x12H\n" +
	"\vclient_auth\x18\x06 \x01(\x0e2'.zengo.config.meta.ServerTLS.ClientAuthR\n" +
	"clientAuth\"C\n" +
	"\n" +
	"ClientAuth\x12\b\n" +
	"\x04NONE\x10\x00\x12\x13\n" +
	"\x0fVERIFY_IF_GIVEN\x10\x01\x12\x16\n" +
	"\x12REQUIRE_AND_VERIFY\x10\x02B Z\x1ezengo/platform/api/config/metab\x06proto3"

var (
	file_config_meta_tls_proto_rawDescOnce sync.Once
	file_config_meta_tls_proto_rawDescData []byte
)

func file_config_meta_tls_proto_rawDescGZIP() []byte {
	file_config_meta_tls_proto_rawDescOnce.Do(func() {
		file_config_meta_tls_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_config_meta_tls_proto_rawDesc), len(file_config_meta_tls_proto_rawDesc)))
	})
	return file_config_meta_tls_proto_rawDescData
}

var file_config_meta_tls_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_config_meta_tls_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_config_meta_tls_proto_goTypes = []any{
	(ServerTLS_ClientAuth)(0), // 0: zengo.config.meta.ServerTLS.ClientAuth
	(*TLSMaterial)(nil),       // 1: zengo.config.meta.TLSMaterial
	(*ClientTLS)(nil),         // 2: zengo.config.meta.ClientTLS
	(*ServerTLS)(nil),         // 3: zengo.config.meta.ServerTLS
}
var file_config_meta_tls_proto_depIdxs = []int32{
	1, // 0: zengo.config.meta.ClientTLS.ca:type_name -> zengo.config.meta.TLSMaterial
	1, // 1: zengo.config.meta.ClientTLS.cert:type_name -> zengo.config.meta.TLSMaterial
	1, // 2: zengo.config.meta.ClientTLS.key:type_name -> zengo.config.meta.TLSMaterial
	1, // 3: zengo.config.meta.ServerTLS.cert:type_name -> zengo.config.meta.TLSMaterial
	1, // 4: zengo.config.meta.ServerTLS.key:type_name -> zengo.config.meta.TLSMaterial
	1, // 5: zengo.config.meta.ServerTLS.ca:type_name -> zengo.config.meta.TLSMaterial
	1, // 6: zengo.config.meta.ServerTLS.client_ca:type_name -> zengo.config.meta.TLSMaterial
	0, // 7: zengo.config.meta.ServerTLS.client_auth:type_name -> zengo.config.meta.ServerTLS.ClientAuth
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_config_meta_tls_proto_init() }
func file_config_meta_tls_proto_init() {
	if File_config_meta_tls_proto != nil {
		return
	}
	file_config_meta_tls_proto_msgTypes[0].OneofWrappers = []any{
		(*TLSMaterial_Path)(nil),
		(*TLSMaterial_InlinePem)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_config_meta_tls_proto_rawDesc), len(file_config_meta_tls_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_config_meta_tls_proto_goTypes,
		DependencyIndexes: file_config_meta_tls_proto_depIdxs,
		EnumInfos:         file_config_meta_tls_proto_enumTypes,
		MessageInfos:      file_config_meta_tls_proto_msgTypes,
	}.Build()
	File_config_meta_tls_proto = out.File
	file_config_meta_tls_proto_goTypes = nil
	file_config_meta_tls_proto_depIdxs = nil
}
