// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: config/logging/config.proto

package logging

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Logging mode.
//
// Mode controls whether logging is configured for production or development.
type Spec_Mode int32

const (
	Spec_PROD Spec_Mode = 0
	Spec_DEV  Spec_Mode = 1
)

// Enum value maps for Spec_Mode.
var (
	Spec_Mode_name = map[int32]string{
		0: "PROD",
		1: "DEV",
	}
	Spec_Mode_value = map[string]int32{
		"PROD": 0,
		"DEV":  1,
	}
)

func (x Spec_Mode) Enum() *Spec_Mode {
	p := new(Spec_Mode)
	*p = x
	return p
}

func (x Spec_Mode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Spec_Mode) Descriptor() protoreflect.EnumDescriptor {
	return file_config_logging_config_proto_enumTypes[0].Descriptor()
}

func (Spec_Mode) Type() protoreflect.EnumType {
	return &file_config_logging_config_proto_enumTypes[0]
}

func (x Spec_Mode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Spec_Mode.Descriptor instead.
func (Spec_Mode) EnumDescriptor() ([]byte, []int) {
	return file_config_logging_config_proto_rawDescGZIP(), []int{1, 0}
}

// Log level.
//
// Level controls the minimum log level emitted by the runtime.
type Spec_Level int32

const (
	Spec_DISABLE Spec_Level = 0
	Spec_DEBUG   Spec_Level = 1
	Spec_INFO    Spec_Level = 2
	Spec_WARN    Spec_Level = 3
	Spec_ERROR   Spec_Level = 4
	Spec_PANIC   Spec_Level = 5
	Spec_FATAL   Spec_Level = 6
)

// Enum value maps for Spec_Level.
var (
	Spec_Level_name = map[int32]string{
		0: "DISABLE",
		1: "DEBUG",
		2: "INFO",
		3: "WARN",
		4: "ERROR",
		5: "PANIC",
		6: "FATAL",
	}
	Spec_Level_value = map[string]int32{
		"DISABLE": 0,
		"DEBUG":   1,
		"INFO":    2,
		"WARN":    3,
		"ERROR":   4,
		"PANIC":   5,
		"FATAL":   6,
	}
)

func (x Spec_Level) Enum() *Spec_Level {
	p := new(Spec_Level)
	*p = x
	return p
}

func (x Spec_Level) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Spec_Level) Descriptor() protoreflect.EnumDescriptor {
	return file_config_logging_config_proto_enumTypes[1].Descriptor()
}

func (Spec_Level) Type() protoreflect.EnumType {
	return &file_config_logging_config_proto_enumTypes[1]
}

func (x Spec_Level) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Spec_Level.Descriptor instead.
func (Spec_Level) EnumDescriptor() ([]byte, []int) {
	return file_config_logging_config_proto_rawDescGZIP(), []int{1, 1}
}

// Log encoding.
//
// Encoding controls the log output format.
type Spec_Encoding int32

const (
	Spec_JSON Spec_Encoding = 0
	Spec_TEXT Spec_Encoding = 1
)

// Enum value maps for Spec_Encoding.
var (
	Spec_Encoding_name = map[int32]string{
		0: "JSON",
		1: "TEXT",
	}
	Spec_Encoding_value = map[string]int32{
		"JSON": 0,
		"TEXT": 1,
	}
)

func (x Spec_Encoding) Enum() *Spec_Encoding {
	p := new(Spec_Encoding)
	*p = x
	return p
}

func (x Spec_Encoding) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Spec_Encoding) Descriptor() protoreflect.EnumDescriptor {
	return file_config_logging_config_proto_enumTypes[2].Descriptor()
}

func (Spec_Encoding) Type() protoreflect.EnumType {
	return &file_config_logging_config_proto_enumTypes[2]
}

func (x Spec_Encoding) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Spec_Encoding.Descriptor instead.
func (Spec_Encoding) EnumDescriptor() ([]byte, []int) {
	return file_config_logging_config_proto_rawDescGZIP(), []int{1, 2}
}

// Logging config document.
//
// Config is the typed logging configuration loaded by the platform runtime.
type Config struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Config kind.
	//
	// kind is the logical config kind used by the loader.
	Kind string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	// Config API version.
	//
	// api_version identifies the document version used for compatibility over time.
	ApiVersion string `protobuf:"bytes,2,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	// Logging settings.
	//
	// spec contains the logger settings consumed by the runtime.
	Spec          *Spec `protobuf:"bytes,3,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_config_logging_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_config_logging_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_config_logging_config_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Config) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *Config) GetSpec() *Spec {
	if x != nil {
		return x.Spec
	}
	return nil
}

// Logging settings.
//
// Spec configures runtime logger behavior.
type Spec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Selected mode.
	//
	// mode selects the runtime logging mode. The zero value behaves like PROD.
	Mode *Spec_Mode `protobuf:"varint,3,opt,name=mode,proto3,enum=zengo.config.logger.Spec_Mode,oneof" json:"mode,omitempty"`
	// Selected level.
	//
	// level selects the minimum emitted log level.
	Level *Spec_Level `protobuf:"varint,1,opt,name=level,proto3,enum=zengo.config.logger.Spec_Level,oneof" json:"level,omitempty"`
	// Selected encoding.
	//
	// encoding selects the log output format.
	Encoding *Spec_Encoding `protobuf:"varint,2,opt,name=encoding,proto3,enum=zengo.config.logger.Spec_Encoding,oneof" json:"encoding,omitempty"`
	// Caller flag.
	//
	// enable_caller includes file and function information in log records.
	EnableCaller *bool `protobuf:"varint,4,opt,name=enable_caller,json=enableCaller,proto3,oneof" json:"enable_caller,omitempty"`
	// Stack trace flag.
	//
	// enable_stack_trace includes stack traces for supported log records.
	EnableStackTrace *bool `protobuf:"varint,5,opt,name=enable_stack_trace,json=enableStackTrace,proto3,oneof" json:"enable_stack_trace,omitempty"`
	// Log file path.
	//
	// log_file_path redirects logs to a file instead of standard output when set.
	LogFilePath   *string `protobuf:"bytes,6,opt,name=log_file_path,json=logFilePath,proto3,oneof" json:"log_file_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Spec) Reset() {
	*x = Spec{}
	mi := &file_config_logging_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Spec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Spec) ProtoMessage() {}

func (x *Spec) ProtoReflect() protoreflect.Message {
	mi := &file_config_logging_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Spec.ProtoReflect.Descriptor instead.
func (*Spec) Descriptor() ([]byte, []int) {
	return file_config_logging_config_proto_rawDescGZIP(), []int{1}
}

func (x *Spec) GetMode() Spec_Mode {
	if x != nil && x.Mode != nil {
		return *x.Mode
	}
	return Spec_PROD
}

func (x *Spec) GetLevel() Spec_Level {
	if x != nil && x.Level != nil {
		return *x.Level
	}
	return Spec_DISABLE
}

func (x *Spec) GetEncoding() Spec_Encoding {
	if x != nil && x.Encoding != nil {
		return *x.Encoding
	}
	return Spec_JSON
}

func (x *Spec) GetEnableCaller() bool {
	if x != nil && x.EnableCaller != nil {
		return *x.EnableCaller
	}
	return false
}

func (x *Spec) GetEnableStackTrace() bool {
	if x != nil && x.EnableStackTrace != nil {
		return *x.EnableStackTrace
	}
	return false
}

func (x *Spec) GetLogFilePath() string {
	if x != nil && x.LogFilePath != nil {
		return *x.LogFilePath
	}
	return ""
}

var File_config_logging_config_proto protoreflect.FileDescriptor

const file_config_logging_config_proto_rawDesc = "" +
	"\n" +
	"\x1bconfig/logging/config.proto\x12\x13zengo.config.logger\"l\n" +
	"\x06Config\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x1f\n" +
	"\vapi_version\x18\x02 \x01(\tR\n" +
	"apiVersion\x12-\n" +
	"\x04spec\x18\x03 \x01(\v2\x19.zengo.config.logger.SpecR\x04spec\"\xb2\x04\n" +
	"\x04Spec\x127\n" +
	"\x04mode\x18\x03 \x01(\x0e2\x1e.zengo.config.logger.Spec.ModeH\x00R\x04mode\x88\x01\x01\x12:\n" +
	"\x05level\x18\x01 \x01(\x0e2\x1f.zengo.config.logger.Spec.LevelH\x01R\x05level\x88\x01\x01\x12C\n" +
	"\bencoding\x18\x02 \x01(\x0e2\".zengo.config.logger.Spec.EncodingH\x02R\bencoding\x88\x01\x01\x12(\n" +
	"\renable_caller\x18\x04 \x01(\bH\x03R\fenableCaller\x88\x01\x01\x121\n" +
	"\x12enable_stack_trace\x18\x05 \x01(\bH\x04R\x10enableStackTrace\x88\x01\x01\x12'\n" +
	"\rlog_file_path\x18\x06 \x01(\tH\x05R\vlogFilePath\x88\x01\x01\"\x19\n" +
	"\x04Mode\x12\b\n" +
	"\x04PROD\x10\x00\x12\a\n" +
	"\x03DEV\x10\x01\"T\n" +
	"\x05Level\x12\v\n" +
	"\aDISABLE\x10\x00\x12\t\n" +
	"\x05DEBUG\x10\x01\x12\b\n" +
	"\x04INFO\x10\x02\x12\b\n" +
	"\x04WARN\x10\x03\x12\t\n" +
	"\x05ERROR\x10\x04\x12\t\n" +
	"\x05PANIC\x10\x05\x12\t\n" +
	"\x05FATAL\x10\x06\"\x1e\n" +
	"\bEncoding\x12\b\n" +
	"\x04JSON\x10\x00\x12\b\n" +
	"\x04TEXT\x10\x01B\a\n" +
	"\x05_modeB\b\n" +
	"\x06_levelB\v\n" +
	"\t_encodingB\x10\n" +
	"\x0e_enable_callerB\x15\n" +
	"\x13_enable_stack_traceB\x10\n" +
	"\x0e_log_file_pathB#Z!zengo/platform/api/config/loggingb\x06proto3"

var (
	file_config_logging_config_proto_rawDescOnce sync.Once
	file_config_logging_config_proto_rawDescData []byte
)

func file_config_logging_config_proto_rawDescGZIP() []byte {
	file_config_logging_config_proto_rawDescOnce.Do(func() {
		file_config_logging_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_config_logging_config_proto_rawDesc), len(file_config_logging_config_proto_rawDesc)))
	})
	return file_config_logging_config_proto_rawDescData
}

var file_config_logging_config_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_config_logging_config_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_config_logging_config_proto_goTypes = []any{
	(Spec_Mode)(0),     // 0: zengo.config.logger.Spec.Mode
	(Spec_Level)(0),    // 1: zengo.config.logger.Spec.Level
	(Spec_Encoding)(0), // 2: zengo.config.logger.Spec.Encoding
	(*Config)(nil),     // 3: zengo.config.logger.Config
	(*Spec)(nil),       // 4: zengo.config.logger.Spec
}
var file_config_logging_config_proto_depIdxs = []int32{
	4, // 0: zengo.config.logger.Config.spec:type_name -> zengo.config.logger.Spec
	0, // 1: zengo.config.logger.Spec.mode:type_name -> zengo.config.logger.Spec.Mode
	1, // 2: zengo.config.logger.Spec.level:type_name -> zengo.config.logger.Spec.Level
	2, // 3: zengo.config.logger.Spec.encoding:type_name -> zengo.config.logger.Spec.Encoding
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_config_logging_config_proto_init() }
func file_config_logging_config_proto_init() {
	if File_config_logging_config_proto != nil {
		return
	}
	file_config_logging_config_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_config_logging_config_proto_rawDesc), len(file_config_logging_config_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_config_logging_config_proto_goTypes,
		DependencyIndexes: file_config_logging_config_proto_depIdxs,
		EnumInfos:         file_config_logging_config_proto_enumTypes,
		MessageInfos:      file_config_logging_config_proto_msgTypes,
	}.Build()
	File_config_logging_config_proto = out.File
	file_config_logging_config_proto_goTypes = nil
	file_config_logging_config_proto_depIdxs = nil
}
