// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: config/db/cassandra/config.proto

package cassandra

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
	meta "zengo/platform/api/config/meta"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Cassandra config document.
//
// Config is the typed Cassandra configuration loaded by the platform runtime.
type Config struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Config kind.
	//
	// kind is the logical config kind used by the loader.
	Kind string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	// Config API version.
	//
	// api_version identifies the document version used for compatibility over time.
	ApiVersion string `protobuf:"bytes,2,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	// Cassandra settings.
	//
	// spec contains the Cassandra connection settings consumed by the runtime.
	Spec          *Spec `protobuf:"bytes,3,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_config_db_cassandra_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_config_db_cassandra_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_config_db_cassandra_config_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Config) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *Config) GetSpec() *Spec {
	if x != nil {
		return x.Spec
	}
	return nil
}

// Cassandra settings.
//
// Spec configures Cassandra connectivity for service runtime components.
type Spec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Cassandra hosts.
	//
	// hosts lists the Cassandra nodes used by the client.
	Hosts []string `protobuf:"bytes,1,rep,name=hosts,proto3" json:"hosts,omitempty"`
	// Cassandra keyspace.
	//
	// keyspace is the logical Cassandra keyspace used by the service.
	Keyspace string `protobuf:"bytes,2,opt,name=keyspace,proto3" json:"keyspace,omitempty"`
	// Cassandra username.
	//
	// username is the optional Cassandra username used for authentication.
	Username *string `protobuf:"bytes,3,opt,name=username,proto3,oneof" json:"username,omitempty"`
	// Cassandra password.
	//
	// password is the optional Cassandra password used for authentication.
	Password *string `protobuf:"bytes,4,opt,name=password,proto3,oneof" json:"password,omitempty"`
	// TLS settings.
	//
	// tls configures TLS and optional mTLS for Cassandra connections.
	Tls           *meta.ClientTLS `protobuf:"bytes,5,opt,name=tls,proto3" json:"tls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Spec) Reset() {
	*x = Spec{}
	mi := &file_config_db_cassandra_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Spec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Spec) ProtoMessage() {}

func (x *Spec) ProtoReflect() protoreflect.Message {
	mi := &file_config_db_cassandra_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Spec.ProtoReflect.Descriptor instead.
func (*Spec) Descriptor() ([]byte, []int) {
	return file_config_db_cassandra_config_proto_rawDescGZIP(), []int{1}
}

func (x *Spec) GetHosts() []string {
	if x != nil {
		return x.Hosts
	}
	return nil
}

func (x *Spec) GetKeyspace() string {
	if x != nil {
		return x.Keyspace
	}
	return ""
}

func (x *Spec) GetUsername() string {
	if x != nil && x.Username != nil {
		return *x.Username
	}
	return ""
}

func (x *Spec) GetPassword() string {
	if x != nil && x.Password != nil {
		return *x.Password
	}
	return ""
}

func (x *Spec) GetTls() *meta.ClientTLS {
	if x != nil {
		return x.Tls
	}
	return nil
}

var File_config_db_cassandra_config_proto protoreflect.FileDescriptor

const file_config_db_cassandra_config_proto_rawDesc = "" +
	"\n" +
	" config/db/cassandra/config.proto\x12\x16zengo.config.cassandra\x1a\x15config/meta/tls.proto\"o\n" +
	"\x06Config\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x1f\n" +
	"\vapi_version\x18\x02 \x01(\tR\n" +
	"apiVersion\x120\n" +
	"\x04spec\x18\x03 \x01(\v2\x1c.zengo.config.cassandra.SpecR\x04spec\"\xc4\x01\n" +
	"\x04Spec\x12\x14\n" +
	"\x05hosts\x18\x01 \x03(\tR\x05hosts\x12\x1a\n" +
	"\bkeyspace\x18\x02 \x01(\tR\bkeyspace\x12\x1f\n" +
	"\busername\x18\x03 \x01(\tH\x00R\busername\x88\x01\x01\x12\x1f\n" +
	"\bpassword\x18\x04 \x01(\tH\x01R\bpassword\x88\x01\x01\x12.\n" +
	"\x03tls\x18\x05 \x01(\v2\x1c.zengo.config.meta.ClientTLSR\x03tlsB\v\n" +
	"\t_usernameB\v\n" +
	"\t_passwordB(Z&zengo/platform/api/config/db/cassandrab\x06proto3"

var (
	file_config_db_cassandra_config_proto_rawDescOnce sync.Once
	file_config_db_cassandra_config_proto_rawDescData []byte
)

func file_config_db_cassandra_config_proto_rawDescGZIP() []byte {
	file_config_db_cassandra_config_proto_rawDescOnce.Do(func() {
		file_config_db_cassandra_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_config_db_cassandra_config_proto_rawDesc), len(file_config_db_cassandra_config_proto_rawDesc)))
	})
	return file_config_db_cassandra_config_proto_rawDescData
}

var file_config_db_cassandra_config_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_config_db_cassandra_config_proto_goTypes = []any{
	(*Config)(nil),         // 0: zengo.config.cassandra.Config
	(*Spec)(nil),           // 1: zengo.config.cassandra.Spec
	(*meta.ClientTLS)(nil), // 2: zengo.config.meta.ClientTLS
}
var file_config_db_cassandra_config_proto_depIdxs = []int32{
	1, // 0: zengo.config.cassandra.Config.spec:type_name -> zengo.config.cassandra.Spec
	2, // 1: zengo.config.cassandra.Spec.tls:type_name -> zengo.config.meta.ClientTLS
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_config_db_cassandra_config_proto_init() }
func file_config_db_cassandra_config_proto_init() {
	if File_config_db_cassandra_config_proto != nil {
		return
	}
	file_config_db_cassandra_config_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_config_db_cassandra_config_proto_rawDesc), len(file_config_db_cassandra_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_config_db_cassandra_config_proto_goTypes,
		DependencyIndexes: file_config_db_cassandra_config_proto_depIdxs,
		MessageInfos:      file_config_db_cassandra_config_proto_msgTypes,
	}.Build()
	File_config_db_cassandra_config_proto = out.File
	file_config_db_cassandra_config_proto_goTypes = nil
	file_config_db_cassandra_config_proto_depIdxs = nil
}
