// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: config/db/redis/config.proto

package redis

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
	meta "zengo/platform/api/config/meta"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Redis config document.
//
// Config is the typed Redis configuration loaded by the platform runtime.
type Config struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Config kind.
	//
	// kind is the logical config kind used by the loader.
	Kind string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	// Config API version.
	//
	// api_version identifies the document version used for compatibility over time.
	ApiVersion string `protobuf:"bytes,2,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	// Redis settings.
	//
	// spec contains the Redis connection settings consumed by the runtime.
	Spec          *Spec `protobuf:"bytes,3,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_config_db_redis_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_config_db_redis_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_config_db_redis_config_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Config) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *Config) GetSpec() *Spec {
	if x != nil {
		return x.Spec
	}
	return nil
}

// Redis settings.
//
// Spec configures Redis connectivity and client tuning.
type Spec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Redis URL.
	//
	// url is a Redis URL, for example redis://:password@localhost:6379/0.
	Url *string `protobuf:"bytes,1,opt,name=url,proto3,oneof" json:"url,omitempty"`
	// Redis addresses.
	//
	// addrs lists cluster or sentinel addresses when url is empty.
	Addrs []string `protobuf:"bytes,2,rep,name=addrs,proto3" json:"addrs,omitempty"`
	// Database index.
	//
	// db is the logical Redis database index.
	Db *int32 `protobuf:"varint,3,opt,name=db,proto3,oneof" json:"db,omitempty"`
	// Redis username.
	//
	// username is the optional Redis username used for authentication.
	Username *string `protobuf:"bytes,4,opt,name=username,proto3,oneof" json:"username,omitempty"`
	// Redis password.
	//
	// password is the optional Redis password used for authentication.
	Password *string `protobuf:"bytes,5,opt,name=password,proto3,oneof" json:"password,omitempty"`
	// TLS settings.
	//
	// tls configures TLS and optional mTLS for Redis connections.
	Tls *meta.ClientTLS `protobuf:"bytes,6,opt,name=tls,proto3" json:"tls,omitempty"`
	// Pool size.
	//
	// pool_size overrides the client connection pool size.
	PoolSize *int32 `protobuf:"varint,7,opt,name=pool_size,json=poolSize,proto3,oneof" json:"pool_size,omitempty"`
	// Dial timeout.
	//
	// dial_timeout bounds initial connection attempts.
	DialTimeout *durationpb.Duration `protobuf:"bytes,8,opt,name=dial_timeout,json=dialTimeout,proto3,oneof" json:"dial_timeout,omitempty"`
	// Read timeout.
	//
	// read_timeout bounds socket read operations.
	ReadTimeout   *durationpb.Duration `protobuf:"bytes,9,opt,name=read_timeout,json=readTimeout,proto3,oneof" json:"read_timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Spec) Reset() {
	*x = Spec{}
	mi := &file_config_db_redis_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Spec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Spec) ProtoMessage() {}

func (x *Spec) ProtoReflect() protoreflect.Message {
	mi := &file_config_db_redis_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Spec.ProtoReflect.Descriptor instead.
func (*Spec) Descriptor() ([]byte, []int) {
	return file_config_db_redis_config_proto_rawDescGZIP(), []int{1}
}

func (x *Spec) GetUrl() string {
	if x != nil && x.Url != nil {
		return *x.Url
	}
	return ""
}

func (x *Spec) GetAddrs() []string {
	if x != nil {
		return x.Addrs
	}
	return nil
}

func (x *Spec) GetDb() int32 {
	if x != nil && x.Db != nil {
		return *x.Db
	}
	return 0
}

func (x *Spec) GetUsername() string {
	if x != nil && x.Username != nil {
		return *x.Username
	}
	return ""
}

func (x *Spec) GetPassword() string {
	if x != nil && x.Password != nil {
		return *x.Password
	}
	return ""
}

func (x *Spec) GetTls() *meta.ClientTLS {
	if x != nil {
		return x.Tls
	}
	return nil
}

func (x *Spec) GetPoolSize() int32 {
	if x != nil && x.PoolSize != nil {
		return *x.PoolSize
	}
	return 0
}

func (x *Spec) GetDialTimeout() *durationpb.Duration {
	if x != nil {
		return x.DialTimeout
	}
	return nil
}

func (x *Spec) GetReadTimeout() *durationpb.Duration {
	if x != nil {
		return x.ReadTimeout
	}
	return nil
}

var File_config_db_redis_config_proto protoreflect.FileDescriptor

const file_config_db_redis_config_proto_rawDesc = "" +
	"\n" +
	"\x1cconfig/db/redis/config.proto\x12\x12zengo.config.redis\x1a\x15config/meta/tls.proto\x1a\x1egoogle/protobuf/duration.proto\"k\n" +
	"\x06Config\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x1f\n" +
	"\vapi_version\x18\x02 \x01(\tR\n" +
	"apiVersion\x12,\n" +
	"\x04spec\x18\x03 \x01(\v2\x18.zengo.config.redis.SpecR\x04spec\"\xbb\x03\n" +
	"\x04Spec\x12\x15\n" +
	"\x03url\x18\x01 \x01(\tH\x00R\x03url\x88\x01\x01\x12\x14\n" +
	"\x05addrs\x18\x02 \x03(\tR\x05addrs\x12\x13\n" +
	"\x02db\x18\x03 \x01(\x05H\x01R\x02db\x88\x01\x01\x12\x1f\n" +
	"\busername\x18\x04 \x01(\tH\x02R\busername\x88\x01\x01\x12\x1f\n" +
	"\bpassword\x18\x05 \x01(\tH\x03R\bpassword\x88\x01\x01\x12.\n" +
	"\x03tls\x18\x06 \x01(\v2\x1c.zengo.config.meta.ClientTLSR\x03tls\x12 \n" +
	"\tpool_size\x18\a \x01(\x05H\x04R\bpoolSize\x88\x01\x01\x12A\n" +
	"\fdial_timeout\x18\b \x01(\v2\x19.google.protobuf.DurationH\x05R\vdialTimeout\x88\x01\x01\x12A\n" +
	"\fread_timeout\x18\t \x01(\v2\x19.google.protobuf.DurationH\x06R\vreadTimeout\x88\x01\x01B\x06\n" +
	"\x04_urlB\x05\n" +
	"\x03_dbB\v\n" +
	"\t_usernameB\v\n" +
	"\t_passwordB\f\n" +
	"\n" +
	"_pool_sizeB\x0f\n" +
	"\r_dial_timeoutB\x0f\n" +
	"\r_read_timeoutB$Z\"zengo/platform/api/config/db/redisb\x06proto3"

var (
	file_config_db_redis_config_proto_rawDescOnce sync.Once
	file_config_db_redis_config_proto_rawDescData []byte
)

func file_config_db_redis_config_proto_rawDescGZIP() []byte {
	file_config_db_redis_config_proto_rawDescOnce.Do(func() {
		file_config_db_redis_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_config_db_redis_config_proto_rawDesc), len(file_config_db_redis_config_proto_rawDesc)))
	})
	return file_config_db_redis_config_proto_rawDescData
}

var file_config_db_redis_config_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_config_db_redis_config_proto_goTypes = []any{
	(*Config)(nil),              // 0: zengo.config.redis.Config
	(*Spec)(nil),                // 1: zengo.config.redis.Spec
	(*meta.ClientTLS)(nil),      // 2: zengo.config.meta.ClientTLS
	(*durationpb.Duration)(nil), // 3: google.protobuf.Duration
}
var file_config_db_redis_config_proto_depIdxs = []int32{
	1, // 0: zengo.config.redis.Config.spec:type_name -> zengo.config.redis.Spec
	2, // 1: zengo.config.redis.Spec.tls:type_name -> zengo.config.meta.ClientTLS
	3, // 2: zengo.config.redis.Spec.dial_timeout:type_name -> google.protobuf.Duration
	3, // 3: zengo.config.redis.Spec.read_timeout:type_name -> google.protobuf.Duration
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_config_db_redis_config_proto_init() }
func file_config_db_redis_config_proto_init() {
	if File_config_db_redis_config_proto != nil {
		return
	}
	file_config_db_redis_config_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_config_db_redis_config_proto_rawDesc), len(file_config_db_redis_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_config_db_redis_config_proto_goTypes,
		DependencyIndexes: file_config_db_redis_config_proto_depIdxs,
		MessageInfos:      file_config_db_redis_config_proto_msgTypes,
	}.Build()
	File_config_db_redis_config_proto = out.File
	file_config_db_redis_config_proto_goTypes = nil
	file_config_db_redis_config_proto_depIdxs = nil
}
