// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: zengo/options/column.proto

package options

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Repository column settings.
//
// Column configures how a proto field maps to a generated Postgres column.
type Column struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Column name override.
	//
	// name overrides the default snake_case column name derived from the field.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// SQL type override.
	//
	// sql_type overrides the inferred Postgres column type.
	SqlType string `protobuf:"bytes,2,opt,name=sql_type,json=sqlType,proto3" json:"sql_type,omitempty"`
	// Primary key marker.
	//
	// primary_key marks the field as the single table primary key.
	PrimaryKey bool `protobuf:"varint,3,opt,name=primary_key,json=primaryKey,proto3" json:"primary_key,omitempty"`
	// Nullable marker.
	//
	// nullable allows the generated column to omit NOT NULL.
	Nullable bool `protobuf:"varint,4,opt,name=nullable,proto3" json:"nullable,omitempty"`
	// Unique marker.
	//
	// unique adds a UNIQUE constraint to the generated column.
	Unique bool `protobuf:"varint,5,opt,name=unique,proto3" json:"unique,omitempty"`
	// SQL default expression.
	//
	// default_sql is copied verbatim into the generated DEFAULT clause.
	DefaultSql string `protobuf:"bytes,6,opt,name=default_sql,json=defaultSql,proto3" json:"default_sql,omitempty"`
	// Ignore marker.
	//
	// ignore excludes the field from generated schema metadata.
	Ignore        bool `protobuf:"varint,7,opt,name=ignore,proto3" json:"ignore,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Column) Reset() {
	*x = Column{}
	mi := &file_zengo_options_column_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Column) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Column) ProtoMessage() {}

func (x *Column) ProtoReflect() protoreflect.Message {
	mi := &file_zengo_options_column_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Column.ProtoReflect.Descriptor instead.
func (*Column) Descriptor() ([]byte, []int) {
	return file_zengo_options_column_proto_rawDescGZIP(), []int{0}
}

func (x *Column) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Column) GetSqlType() string {
	if x != nil {
		return x.SqlType
	}
	return ""
}

func (x *Column) GetPrimaryKey() bool {
	if x != nil {
		return x.PrimaryKey
	}
	return false
}

func (x *Column) GetNullable() bool {
	if x != nil {
		return x.Nullable
	}
	return false
}

func (x *Column) GetUnique() bool {
	if x != nil {
		return x.Unique
	}
	return false
}

func (x *Column) GetDefaultSql() string {
	if x != nil {
		return x.DefaultSql
	}
	return ""
}

func (x *Column) GetIgnore() bool {
	if x != nil {
		return x.Ignore
	}
	return false
}

var file_zengo_options_column_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*Column)(nil),
		Field:         50006,
		Name:          "zengo.options.column",
		Tag:           "bytes,50006,opt,name=column",
		Filename:      "zengo/options/column.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional zengo.options.Column column = 50006;
	E_Column = &file_zengo_options_column_proto_extTypes[0]
)

var File_zengo_options_column_proto protoreflect.FileDescriptor

const file_zengo_options_column_proto_rawDesc = "" +
	"\n" +
	"\x1azengo/options/column.proto\x12\rzengo.options\x1a google/protobuf/descriptor.proto\"\xc5\x01\n" +
	"\x06Column\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\bsql_type\x18\x02 \x01(\tR\asqlType\x12\x1f\n" +
	"\vprimary_key\x18\x03 \x01(\bR\n" +
	"primaryKey\x12\x1a\n" +
	"\bnullable\x18\x04 \x01(\bR\bnullable\x12\x16\n" +
	"\x06unique\x18\x05 \x01(\bR\x06unique\x12\x1f\n" +
	"\vdefault_sql\x18\x06 \x01(\tR\n" +
	"defaultSql\x12\x16\n" +
	"\x06ignore\x18\a \x01(\bR\x06ignore:N\n" +
	"\x06column\x12\x1d.google.protobuf.FieldOptions\x18ֆ\x03 \x01(\v2\x15.zengo.options.ColumnR\x06columnB*Z(zengo/platform/api/zengo/options;optionsb\x06proto3"

var (
	file_zengo_options_column_proto_rawDescOnce sync.Once
	file_zengo_options_column_proto_rawDescData []byte
)

func file_zengo_options_column_proto_rawDescGZIP() []byte {
	file_zengo_options_column_proto_rawDescOnce.Do(func() {
		file_zengo_options_column_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_zengo_options_column_proto_rawDesc), len(file_zengo_options_column_proto_rawDesc)))
	})
	return file_zengo_options_column_proto_rawDescData
}

var file_zengo_options_column_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_zengo_options_column_proto_goTypes = []any{
	(*Column)(nil),                    // 0: zengo.options.Column
	(*descriptorpb.FieldOptions)(nil), // 1: google.protobuf.FieldOptions
}
var file_zengo_options_column_proto_depIdxs = []int32{
	1, // 0: zengo.options.column:extendee -> google.protobuf.FieldOptions
	0, // 1: zengo.options.column:type_name -> zengo.options.Column
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	1, // [1:2] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_zengo_options_column_proto_init() }
func file_zengo_options_column_proto_init() {
	if File_zengo_options_column_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_zengo_options_column_proto_rawDesc), len(file_zengo_options_column_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_zengo_options_column_proto_goTypes,
		DependencyIndexes: file_zengo_options_column_proto_depIdxs,
		MessageInfos:      file_zengo_options_column_proto_msgTypes,
		ExtensionInfos:    file_zengo_options_column_proto_extTypes,
	}.Build()
	File_zengo_options_column_proto = out.File
	file_zengo_options_column_proto_goTypes = nil
	file_zengo_options_column_proto_depIdxs = nil
}
