// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: zengo/options/convert.proto

package options

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Conversion mode.
//
// Mode controls whether conversion is automatic or requires manual code.
type ConvertPolicy_Mode int32

const (
	ConvertPolicy_AUTO   ConvertPolicy_Mode = 0
	ConvertPolicy_MANUAL ConvertPolicy_Mode = 1
)

// Enum value maps for ConvertPolicy_Mode.
var (
	ConvertPolicy_Mode_name = map[int32]string{
		0: "AUTO",
		1: "MANUAL",
	}
	ConvertPolicy_Mode_value = map[string]int32{
		"AUTO":   0,
		"MANUAL": 1,
	}
)

func (x ConvertPolicy_Mode) Enum() *ConvertPolicy_Mode {
	p := new(ConvertPolicy_Mode)
	*p = x
	return p
}

func (x ConvertPolicy_Mode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConvertPolicy_Mode) Descriptor() protoreflect.EnumDescriptor {
	return file_zengo_options_convert_proto_enumTypes[0].Descriptor()
}

func (ConvertPolicy_Mode) Type() protoreflect.EnumType {
	return &file_zengo_options_convert_proto_enumTypes[0]
}

func (x ConvertPolicy_Mode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConvertPolicy_Mode.Descriptor instead.
func (ConvertPolicy_Mode) EnumDescriptor() ([]byte, []int) {
	return file_zengo_options_convert_proto_rawDescGZIP(), []int{1, 0}
}

// Legacy field mapping.
//
// FieldMap configures legacy field-name mapping for conversion generation.
type FieldMap struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Legacy field name.
	//
	// legacy_name is the field name expected by the legacy API contract.
	LegacyName    string `protobuf:"bytes,1,opt,name=legacy_name,json=legacyName,proto3" json:"legacy_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldMap) Reset() {
	*x = FieldMap{}
	mi := &file_zengo_options_convert_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldMap) ProtoMessage() {}

func (x *FieldMap) ProtoReflect() protoreflect.Message {
	mi := &file_zengo_options_convert_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldMap.ProtoReflect.Descriptor instead.
func (*FieldMap) Descriptor() ([]byte, []int) {
	return file_zengo_options_convert_proto_rawDescGZIP(), []int{0}
}

func (x *FieldMap) GetLegacyName() string {
	if x != nil {
		return x.LegacyName
	}
	return ""
}

// Conversion policy.
//
// ConvertPolicy configures whether message conversion may be generated automatically.
type ConvertPolicy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Selected mode.
	//
	// mode selects the conversion strategy.
	Mode ConvertPolicy_Mode `protobuf:"varint,1,opt,name=mode,proto3,enum=zengo.options.ConvertPolicy_Mode" json:"mode,omitempty"`
	// Manual conversion file.
	//
	// manual_file points to the service-local file that implements manual conversion.
	ManualFile    string `protobuf:"bytes,2,opt,name=manual_file,json=manualFile,proto3" json:"manual_file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConvertPolicy) Reset() {
	*x = ConvertPolicy{}
	mi := &file_zengo_options_convert_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvertPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertPolicy) ProtoMessage() {}

func (x *ConvertPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_zengo_options_convert_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertPolicy.ProtoReflect.Descriptor instead.
func (*ConvertPolicy) Descriptor() ([]byte, []int) {
	return file_zengo_options_convert_proto_rawDescGZIP(), []int{1}
}

func (x *ConvertPolicy) GetMode() ConvertPolicy_Mode {
	if x != nil {
		return x.Mode
	}
	return ConvertPolicy_AUTO
}

func (x *ConvertPolicy) GetManualFile() string {
	if x != nil {
		return x.ManualFile
	}
	return ""
}

var file_zengo_options_convert_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*FieldMap)(nil),
		Field:         50004,
		Name:          "zengo.options.field_map",
		Tag:           "bytes,50004,opt,name=field_map",
		Filename:      "zengo/options/convert.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*ConvertPolicy)(nil),
		Field:         50005,
		Name:          "zengo.options.convert",
		Tag:           "bytes,50005,opt,name=convert",
		Filename:      "zengo/options/convert.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional zengo.options.FieldMap field_map = 50004;
	E_FieldMap = &file_zengo_options_convert_proto_extTypes[0]
)

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional zengo.options.ConvertPolicy convert = 50005;
	E_Convert = &file_zengo_options_convert_proto_extTypes[1]
)

var File_zengo_options_convert_proto protoreflect.FileDescriptor

const file_zengo_options_convert_proto_rawDesc = "" +
	"\n" +
	"\x1bzengo/options/convert.proto\x12\rzengo.options\x1a google/protobuf/descriptor.proto\"+\n" +
	"\bFieldMap\x12\x1f\n" +
	"\vlegacy_name\x18\x01 \x01(\tR\n" +
	"legacyName\"\x85\x01\n" +
	"\rConvertPolicy\x125\n" +
	"\x04mode\x18\x01 \x01(\x0e2!.zengo.options.ConvertPolicy.ModeR\x04mode\x12\x1f\n" +
	"\vmanual_file\x18\x02 \x01(\tR\n" +
	"manualFile\"\x1c\n" +
	"\x04Mode\x12\b\n" +
	"\x04AUTO\x10\x00\x12\n" +
	"\n" +
	"\x06MANUAL\x10\x01:U\n" +
	"\tfield_map\x12\x1d.google.protobuf.FieldOptions\x18Ԇ\x03 \x01(\v2\x17.zengo.options.FieldMapR\bfieldMap:Y\n" +
	"\aconvert\x12\x1f.google.protobuf.MessageOptions\x18Ն\x03 \x01(\v2\x1c.zengo.options.ConvertPolicyR\aconvertB*Z(zengo/platform/api/zengo/options;optionsb\x06proto3"

var (
	file_zengo_options_convert_proto_rawDescOnce sync.Once
	file_zengo_options_convert_proto_rawDescData []byte
)

func file_zengo_options_convert_proto_rawDescGZIP() []byte {
	file_zengo_options_convert_proto_rawDescOnce.Do(func() {
		file_zengo_options_convert_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_zengo_options_convert_proto_rawDesc), len(file_zengo_options_convert_proto_rawDesc)))
	})
	return file_zengo_options_convert_proto_rawDescData
}

var file_zengo_options_convert_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_zengo_options_convert_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_zengo_options_convert_proto_goTypes = []any{
	(ConvertPolicy_Mode)(0),             // 0: zengo.options.ConvertPolicy.Mode
	(*FieldMap)(nil),                    // 1: zengo.options.FieldMap
	(*ConvertPolicy)(nil),               // 2: zengo.options.ConvertPolicy
	(*descriptorpb.FieldOptions)(nil),   // 3: google.protobuf.FieldOptions
	(*descriptorpb.MessageOptions)(nil), // 4: google.protobuf.MessageOptions
}
var file_zengo_options_convert_proto_depIdxs = []int32{
	0, // 0: zengo.options.ConvertPolicy.mode:type_name -> zengo.options.ConvertPolicy.Mode
	3, // 1: zengo.options.field_map:extendee -> google.protobuf.FieldOptions
	4, // 2: zengo.options.convert:extendee -> google.protobuf.MessageOptions
	1, // 3: zengo.options.field_map:type_name -> zengo.options.FieldMap
	2, // 4: zengo.options.convert:type_name -> zengo.options.ConvertPolicy
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	3, // [3:5] is the sub-list for extension type_name
	1, // [1:3] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_zengo_options_convert_proto_init() }
func file_zengo_options_convert_proto_init() {
	if File_zengo_options_convert_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_zengo_options_convert_proto_rawDesc), len(file_zengo_options_convert_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_zengo_options_convert_proto_goTypes,
		DependencyIndexes: file_zengo_options_convert_proto_depIdxs,
		EnumInfos:         file_zengo_options_convert_proto_enumTypes,
		MessageInfos:      file_zengo_options_convert_proto_msgTypes,
		ExtensionInfos:    file_zengo_options_convert_proto_extTypes,
	}.Build()
	File_zengo_options_convert_proto = out.File
	file_zengo_options_convert_proto_goTypes = nil
	file_zengo_options_convert_proto_depIdxs = nil
}
