// Code generated by zengo gen. DO NOT EDIT.

package main

import (
	"context"
	"flag"
	"fmt"
	"log/slog"
	"os"
	"os/signal"
	"syscall"

	loggingcfg "zengo/platform/api/config/logging"
	tracingcfg "zengo/platform/api/config/tracing"
	"zengo/platform/sdk/config"
	"zengo/platform/sdk/service"
	"zengo/platform/sdk/transport/queue/kafka"

	"github.com/zengo/notification-service/gen/zengo"
	"github.com/zengo/notification-service/internal/notification"
)

func main() {
	err := run()
	if err != nil {
		fmt.Fprintf(os.Stderr, "%v\n", err)
		os.Exit(1)
	}
}

func run() error {
	versionFlag := flag.Bool("version", false, "print build metadata and exit")
	flag.Parse()
	if *versionFlag {
		err := service.PrintVersion(os.Stdout, "notification-service")
		if err != nil {
			return fmt.Errorf("print build info: %w", err)
		}
		return nil
	}

	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer stop()
	var err error
	cleanups := []func() error{}
	cfgLoader := config.NewLoader("configs")

	repo := notification.NewRepository(nil)

	kafkaCfg := kafkaConfig(cfgLoader)
	brokers := kafka.Brokers(kafkaCfg)
	var producer *kafka.Producer
	producer, err = kafka.NewProducerFromConfig(kafkaCfg)
	if err != nil {
		return cleanupAndReturn(err, cleanups)
	}
	cleanups = append(cleanups, producer.Close)

	hubHandler := notification.NewHandler(repo, producer, brokers)

	var consumer *kafka.Consumer
	consumer, err = kafka.NewConsumerFromConfig("notification-service", kafkaCfg)
	if err != nil {
		return cleanupAndReturn(err, cleanups)
	}
	cleanups = append(cleanups, consumer.Close)
	deps := zengo.Dependencies{KafkaBrokers: brokers, Producer: producer}
	err = notification.RegisterKafka(consumer, deps, hubHandler)
	if err != nil {
		return cleanupAndReturn(err, cleanups)
	}

	grpcServer, grpcErr := service.NewGRPCServerWithOptions(service.GRPCServerOptions{
		EnableTracing: true,
		TLS:           nil,
	})
	if grpcErr != nil {
		return cleanupAndReturn(grpcErr, cleanups)
	}
	zengo.RegisterGRPC(grpcServer, hubHandler)
	zengo.RegisterHubGRPC(grpcServer, hubHandler)

	restGroups := make([]service.RESTRouteGroup, 0, 2)
	registers := zengo.GatewayRegisterFuncs()
	if len(registers) > 0 {
		restGroups = append(restGroups, service.RESTRouteGroup{
			GRPCAddr: fmt.Sprintf("127.0.0.1:%d", 9091),
			Register: registers,
		})
	}
	restGroups = append(restGroups, service.RESTRouteGroup{
		Prefix:   "/hub",
		GRPCAddr: fmt.Sprintf("127.0.0.1:%d", 9091),
		Register: zengo.HubGatewayRegisterFuncs(),
	})

	var runtime *service.Runtime
	runtime, err = service.New(ctx, service.Options{
		Name:       "notification-service",
		Metrics:    true,
		Tracing:    true,
		Logging:    loggingConfig(cfgLoader),
		TracingCfg: tracingConfig(cfgLoader),
		GRPC: &service.GRPC{
			Addr:             fmt.Sprintf(":%d", 9091),
			Server:           grpcServer,
			EnableReflection: true,
		},
		REST: &service.REST{
			Addr:          fmt.Sprintf(":%d", 8081),
			GRPCClientTLS: nil,
			TLS:           nil,
			Groups:        restGroups,
		},
		Readiness: map[string]service.Check{},
		Cleanup: []service.Hook{
			func(context.Context) error { return producer.Close() },
			func(context.Context) error { return consumer.Close() },
		},
	})
	if err != nil {
		return cleanupAndReturn(err, cleanups)
	}
	slog.Info("starting service", "name", "notification-service")
	return runtime.Run(ctx)
}

func cleanupAndReturn(cause error, cleanups []func() error) error {
	for i := len(cleanups) - 1; i >= 0; i-- {
		err := cleanups[i]()
		if err != nil {
			cause = fmt.Errorf("%w; cleanup: %w", cause, err)
		}
	}
	return cause
}

func loggingConfig(loader *config.Loader) *loggingcfg.Config {
	cfg, err := loader.Logging("logging")
	if err != nil {
		return nil
	}
	return cfg
}

func tracingConfig(loader *config.Loader) *tracingcfg.Config {
	cfg, err := loader.Tracing("tracing")
	if err != nil {
		slog.Warn("tracing config unavailable, using stdout fallback", "err", err)
		return nil
	}
	return cfg
}

func kafkaConfig(loader *config.Loader) *kafka.Config {
	return kafka.ConfigFromLoader(loader, "kafka", []string{"localhost:9092"})
}
