// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: config/db/postgres/config.proto

package postgres

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
	meta "zengo/platform/api/config/meta"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Database access mode.
//
// Mode describes the intended database access pattern for the service.
type Spec_Mode int32

const (
	Spec_RO Spec_Mode = 0
	Spec_RW Spec_Mode = 1
)

// Enum value maps for Spec_Mode.
var (
	Spec_Mode_name = map[int32]string{
		0: "RO",
		1: "RW",
	}
	Spec_Mode_value = map[string]int32{
		"RO": 0,
		"RW": 1,
	}
)

func (x Spec_Mode) Enum() *Spec_Mode {
	p := new(Spec_Mode)
	*p = x
	return p
}

func (x Spec_Mode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Spec_Mode) Descriptor() protoreflect.EnumDescriptor {
	return file_config_db_postgres_config_proto_enumTypes[0].Descriptor()
}

func (Spec_Mode) Type() protoreflect.EnumType {
	return &file_config_db_postgres_config_proto_enumTypes[0]
}

func (x Spec_Mode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Spec_Mode.Descriptor instead.
func (Spec_Mode) EnumDescriptor() ([]byte, []int) {
	return file_config_db_postgres_config_proto_rawDescGZIP(), []int{1, 0}
}

// TLS mode.
//
// SSLMode controls TLS behavior for PostgreSQL connections.
type Spec_SSLMode int32

const (
	Spec_DISABLE     Spec_SSLMode = 0
	Spec_PREFER      Spec_SSLMode = 1
	Spec_ALLOW       Spec_SSLMode = 2
	Spec_REQUIRE     Spec_SSLMode = 3
	Spec_VERIFY_CA   Spec_SSLMode = 4
	Spec_VERIFY_FULL Spec_SSLMode = 5
)

// Enum value maps for Spec_SSLMode.
var (
	Spec_SSLMode_name = map[int32]string{
		0: "DISABLE",
		1: "PREFER",
		2: "ALLOW",
		3: "REQUIRE",
		4: "VERIFY_CA",
		5: "VERIFY_FULL",
	}
	Spec_SSLMode_value = map[string]int32{
		"DISABLE":     0,
		"PREFER":      1,
		"ALLOW":       2,
		"REQUIRE":     3,
		"VERIFY_CA":   4,
		"VERIFY_FULL": 5,
	}
)

func (x Spec_SSLMode) Enum() *Spec_SSLMode {
	p := new(Spec_SSLMode)
	*p = x
	return p
}

func (x Spec_SSLMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Spec_SSLMode) Descriptor() protoreflect.EnumDescriptor {
	return file_config_db_postgres_config_proto_enumTypes[1].Descriptor()
}

func (Spec_SSLMode) Type() protoreflect.EnumType {
	return &file_config_db_postgres_config_proto_enumTypes[1]
}

func (x Spec_SSLMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Spec_SSLMode.Descriptor instead.
func (Spec_SSLMode) EnumDescriptor() ([]byte, []int) {
	return file_config_db_postgres_config_proto_rawDescGZIP(), []int{1, 1}
}

// PostgreSQL config document.
//
// Config is the typed PostgreSQL configuration loaded by the platform runtime.
type Config struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Config kind.
	//
	// kind is the logical config kind used by the loader.
	Kind string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	// Config API version.
	//
	// api_version identifies the document version used for compatibility over time.
	ApiVersion string `protobuf:"bytes,2,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	// PostgreSQL settings.
	//
	// spec contains the PostgreSQL connection settings consumed by the runtime.
	Spec          *Spec `protobuf:"bytes,3,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_config_db_postgres_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_config_db_postgres_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_config_db_postgres_config_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Config) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *Config) GetSpec() *Spec {
	if x != nil {
		return x.Spec
	}
	return nil
}

// PostgreSQL settings.
//
// Spec configures PostgreSQL connectivity and optional migration behavior.
type Spec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Access mode.
	//
	// mode selects read-only or read-write access semantics for the connection.
	Mode Spec_Mode `protobuf:"varint,1,opt,name=mode,proto3,enum=zengo.config.db.postgres.Spec_Mode" json:"mode,omitempty"`
	// Database host.
	//
	// host is the database host or IP address.
	Host string `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	// Database port.
	//
	// port is the PostgreSQL port. When omitted, clients default to 5432.
	Port *int32 `protobuf:"varint,3,opt,name=port,proto3,oneof" json:"port,omitempty"`
	// Database name.
	//
	// db_name is the database name used for the connection.
	DbName string `protobuf:"bytes,4,opt,name=db_name,json=dbName,proto3" json:"db_name,omitempty"`
	// Database user.
	//
	// user_name is the database user used for the connection.
	UserName string `protobuf:"bytes,5,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	// Database password.
	//
	// password is the database password. It may be empty.
	Password *string `protobuf:"bytes,6,opt,name=password,proto3,oneof" json:"password,omitempty"`
	// Selected TLS mode.
	//
	// ssl_mode selects PostgreSQL TLS behavior. The zero value is DISABLE.
	SslMode *Spec_SSLMode `protobuf:"varint,7,opt,name=ssl_mode,json=sslMode,proto3,enum=zengo.config.db.postgres.Spec_SSLMode,oneof" json:"ssl_mode,omitempty"`
	// Search path schemas.
	//
	// schemas lists schema names appended to the search path in order.
	Schemas []string `protobuf:"bytes,8,rep,name=schemas,proto3" json:"schemas,omitempty"`
	// Service name.
	//
	// service_name is an optional logical service name for logs and metrics.
	ServiceName *string `protobuf:"bytes,9,opt,name=service_name,json=serviceName,proto3,oneof" json:"service_name,omitempty"`
	// Metrics flag.
	//
	// enable_metrics enables database metrics collection when supported.
	EnableMetrics bool `protobuf:"varint,10,opt,name=enable_metrics,json=enableMetrics,proto3" json:"enable_metrics,omitempty"`
	// Connection tuning.
	//
	// connection fine-tunes pool sizing and connection lifetimes.
	Connection *Connection `protobuf:"bytes,11,opt,name=connection,proto3,oneof" json:"connection,omitempty"`
	// Migration settings.
	//
	// migration configures migration source paths when the service applies migrations.
	Migration *Migration `protobuf:"bytes,12,opt,name=migration,proto3,oneof" json:"migration,omitempty"`
	// TLS settings.
	//
	// tls configures CA and client-certificate material used together with ssl_mode.
	Tls           *meta.ClientTLS `protobuf:"bytes,13,opt,name=tls,proto3" json:"tls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Spec) Reset() {
	*x = Spec{}
	mi := &file_config_db_postgres_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Spec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Spec) ProtoMessage() {}

func (x *Spec) ProtoReflect() protoreflect.Message {
	mi := &file_config_db_postgres_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Spec.ProtoReflect.Descriptor instead.
func (*Spec) Descriptor() ([]byte, []int) {
	return file_config_db_postgres_config_proto_rawDescGZIP(), []int{1}
}

func (x *Spec) GetMode() Spec_Mode {
	if x != nil {
		return x.Mode
	}
	return Spec_RO
}

func (x *Spec) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Spec) GetPort() int32 {
	if x != nil && x.Port != nil {
		return *x.Port
	}
	return 0
}

func (x *Spec) GetDbName() string {
	if x != nil {
		return x.DbName
	}
	return ""
}

func (x *Spec) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *Spec) GetPassword() string {
	if x != nil && x.Password != nil {
		return *x.Password
	}
	return ""
}

func (x *Spec) GetSslMode() Spec_SSLMode {
	if x != nil && x.SslMode != nil {
		return *x.SslMode
	}
	return Spec_DISABLE
}

func (x *Spec) GetSchemas() []string {
	if x != nil {
		return x.Schemas
	}
	return nil
}

func (x *Spec) GetServiceName() string {
	if x != nil && x.ServiceName != nil {
		return *x.ServiceName
	}
	return ""
}

func (x *Spec) GetEnableMetrics() bool {
	if x != nil {
		return x.EnableMetrics
	}
	return false
}

func (x *Spec) GetConnection() *Connection {
	if x != nil {
		return x.Connection
	}
	return nil
}

func (x *Spec) GetMigration() *Migration {
	if x != nil {
		return x.Migration
	}
	return nil
}

func (x *Spec) GetTls() *meta.ClientTLS {
	if x != nil {
		return x.Tls
	}
	return nil
}

// PostgreSQL connection tuning.
//
// Connection configures PostgreSQL pool sizing and connection lifetimes.
type Connection struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Maximum idle connections.
	//
	// max_idle is the maximum number of idle connections kept by the client.
	MaxIdle uint32 `protobuf:"varint,1,opt,name=max_idle,json=maxIdle,proto3" json:"max_idle,omitempty"`
	// Minimum open connections.
	//
	// min_open is the minimum number of open connections kept by the client.
	MinOpen uint32 `protobuf:"varint,2,opt,name=min_open,json=minOpen,proto3" json:"min_open,omitempty"`
	// Maximum open connections.
	//
	// max_open is the maximum number of open connections allowed by the client.
	MaxOpen uint32 `protobuf:"varint,3,opt,name=max_open,json=maxOpen,proto3" json:"max_open,omitempty"`
	// Maximum connection lifetime.
	//
	// max_life_time is the maximum lifetime of a single connection.
	MaxLifeTime *durationpb.Duration `protobuf:"bytes,4,opt,name=max_life_time,json=maxLifeTime,proto3" json:"max_life_time,omitempty"`
	// Maximum idle time.
	//
	// max_idle_time is the maximum time a connection may remain idle.
	MaxIdleTime   *durationpb.Duration `protobuf:"bytes,5,opt,name=max_idle_time,json=maxIdleTime,proto3" json:"max_idle_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Connection) Reset() {
	*x = Connection{}
	mi := &file_config_db_postgres_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Connection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Connection) ProtoMessage() {}

func (x *Connection) ProtoReflect() protoreflect.Message {
	mi := &file_config_db_postgres_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Connection.ProtoReflect.Descriptor instead.
func (*Connection) Descriptor() ([]byte, []int) {
	return file_config_db_postgres_config_proto_rawDescGZIP(), []int{2}
}

func (x *Connection) GetMaxIdle() uint32 {
	if x != nil {
		return x.MaxIdle
	}
	return 0
}

func (x *Connection) GetMinOpen() uint32 {
	if x != nil {
		return x.MinOpen
	}
	return 0
}

func (x *Connection) GetMaxOpen() uint32 {
	if x != nil {
		return x.MaxOpen
	}
	return 0
}

func (x *Connection) GetMaxLifeTime() *durationpb.Duration {
	if x != nil {
		return x.MaxLifeTime
	}
	return nil
}

func (x *Connection) GetMaxIdleTime() *durationpb.Duration {
	if x != nil {
		return x.MaxIdleTime
	}
	return nil
}

// Migration locations.
//
// Migration lists migration locations used by the service.
type Migration struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Migration paths.
	//
	// paths lists directories that contain migration files.
	Paths         []string `protobuf:"bytes,1,rep,name=paths,proto3" json:"paths,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Migration) Reset() {
	*x = Migration{}
	mi := &file_config_db_postgres_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Migration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Migration) ProtoMessage() {}

func (x *Migration) ProtoReflect() protoreflect.Message {
	mi := &file_config_db_postgres_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Migration.ProtoReflect.Descriptor instead.
func (*Migration) Descriptor() ([]byte, []int) {
	return file_config_db_postgres_config_proto_rawDescGZIP(), []int{3}
}

func (x *Migration) GetPaths() []string {
	if x != nil {
		return x.Paths
	}
	return nil
}

var File_config_db_postgres_config_proto protoreflect.FileDescriptor

const file_config_db_postgres_config_proto_rawDesc = "" +
	"\n" +
	"\x1fconfig/db/postgres/config.proto\x12\x18zengo.config.db.postgres\x1a\x15config/meta/tls.proto\x1a\x1egoogle/protobuf/duration.proto\"q\n" +
	"\x06Config\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x1f\n" +
	"\vapi_version\x18\x02 \x01(\tR\n" +
	"apiVersion\x122\n" +
	"\x04spec\x18\x03 \x01(\v2\x1e.zengo.config.db.postgres.SpecR\x04spec\"\xfc\x05\n" +
	"\x04Spec\x127\n" +
	"\x04mode\x18\x01 \x01(\x0e2#.zengo.config.db.postgres.Spec.ModeR\x04mode\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x17\n" +
	"\x04port\x18\x03 \x01(\x05H\x00R\x04port\x88\x01\x01\x12\x17\n" +
	"\adb_name\x18\x04 \x01(\tR\x06dbName\x12\x1b\n" +
	"\tuser_name\x18\x05 \x01(\tR\buserName\x12\x1f\n" +
	"\bpassword\x18\x06 \x01(\tH\x01R\bpassword\x88\x01\x01\x12F\n" +
	"\bssl_mode\x18\a \x01(\x0e2&.zengo.config.db.postgres.Spec.SSLModeH\x02R\asslMode\x88\x01\x01\x12\x18\n" +
	"\aschemas\x18\b \x03(\tR\aschemas\x12&\n" +
	"\fservice_name\x18\t \x01(\tH\x03R\vserviceName\x88\x01\x01\x12%\n" +
	"\x0eenable_metrics\x18\n" +
	" \x01(\bR\renableMetrics\x12I\n" +
	"\n" +
	"connection\x18\v \x01(\v2$.zengo.config.db.postgres.ConnectionH\x04R\n" +
	"connection\x88\x01\x01\x12F\n" +
	"\tmigration\x18\f \x01(\v2#.zengo.config.db.postgres.MigrationH\x05R\tmigration\x88\x01\x01\x12.\n" +
	"\x03tls\x18\r \x01(\v2\x1c.zengo.config.meta.ClientTLSR\x03tls\"\x16\n" +
	"\x04Mode\x12\x06\n" +
	"\x02RO\x10\x00\x12\x06\n" +
	"\x02RW\x10\x01\"Z\n" +
	"\aSSLMode\x12\v\n" +
	"\aDISABLE\x10\x00\x12\n" +
	"\n" +
	"\x06PREFER\x10\x01\x12\t\n" +
	"\x05ALLOW\x10\x02\x12\v\n" +
	"\aREQUIRE\x10\x03\x12\r\n" +
	"\tVERIFY_CA\x10\x04\x12\x0f\n" +
	"\vVERIFY_FULL\x10\x05B\a\n" +
	"\x05_portB\v\n" +
	"\t_passwordB\v\n" +
	"\t_ssl_modeB\x0f\n" +
	"\r_service_nameB\r\n" +
	"\v_connectionB\f\n" +
	"\n" +
	"_migration\"\xdb\x01\n" +
	"\n" +
	"Connection\x12\x19\n" +
	"\bmax_idle\x18\x01 \x01(\rR\amaxIdle\x12\x19\n" +
	"\bmin_open\x18\x02 \x01(\rR\aminOpen\x12\x19\n" +
	"\bmax_open\x18\x03 \x01(\rR\amaxOpen\x12=\n" +
	"\rmax_life_time\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\vmaxLifeTime\x12=\n" +
	"\rmax_idle_time\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\vmaxIdleTime\"!\n" +
	"\tMigration\x12\x14\n" +
	"\x05paths\x18\x01 \x03(\tR\x05pathsB'Z%zengo/platform/api/config/db/postgresb\x06proto3"

var (
	file_config_db_postgres_config_proto_rawDescOnce sync.Once
	file_config_db_postgres_config_proto_rawDescData []byte
)

func file_config_db_postgres_config_proto_rawDescGZIP() []byte {
	file_config_db_postgres_config_proto_rawDescOnce.Do(func() {
		file_config_db_postgres_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_config_db_postgres_config_proto_rawDesc), len(file_config_db_postgres_config_proto_rawDesc)))
	})
	return file_config_db_postgres_config_proto_rawDescData
}

var file_config_db_postgres_config_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_config_db_postgres_config_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_config_db_postgres_config_proto_goTypes = []any{
	(Spec_Mode)(0),              // 0: zengo.config.db.postgres.Spec.Mode
	(Spec_SSLMode)(0),           // 1: zengo.config.db.postgres.Spec.SSLMode
	(*Config)(nil),              // 2: zengo.config.db.postgres.Config
	(*Spec)(nil),                // 3: zengo.config.db.postgres.Spec
	(*Connection)(nil),          // 4: zengo.config.db.postgres.Connection
	(*Migration)(nil),           // 5: zengo.config.db.postgres.Migration
	(*meta.ClientTLS)(nil),      // 6: zengo.config.meta.ClientTLS
	(*durationpb.Duration)(nil), // 7: google.protobuf.Duration
}
var file_config_db_postgres_config_proto_depIdxs = []int32{
	3, // 0: zengo.config.db.postgres.Config.spec:type_name -> zengo.config.db.postgres.Spec
	0, // 1: zengo.config.db.postgres.Spec.mode:type_name -> zengo.config.db.postgres.Spec.Mode
	1, // 2: zengo.config.db.postgres.Spec.ssl_mode:type_name -> zengo.config.db.postgres.Spec.SSLMode
	4, // 3: zengo.config.db.postgres.Spec.connection:type_name -> zengo.config.db.postgres.Connection
	5, // 4: zengo.config.db.postgres.Spec.migration:type_name -> zengo.config.db.postgres.Migration
	6, // 5: zengo.config.db.postgres.Spec.tls:type_name -> zengo.config.meta.ClientTLS
	7, // 6: zengo.config.db.postgres.Connection.max_life_time:type_name -> google.protobuf.Duration
	7, // 7: zengo.config.db.postgres.Connection.max_idle_time:type_name -> google.protobuf.Duration
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_config_db_postgres_config_proto_init() }
func file_config_db_postgres_config_proto_init() {
	if File_config_db_postgres_config_proto != nil {
		return
	}
	file_config_db_postgres_config_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_config_db_postgres_config_proto_rawDesc), len(file_config_db_postgres_config_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_config_db_postgres_config_proto_goTypes,
		DependencyIndexes: file_config_db_postgres_config_proto_depIdxs,
		EnumInfos:         file_config_db_postgres_config_proto_enumTypes,
		MessageInfos:      file_config_db_postgres_config_proto_msgTypes,
	}.Build()
	File_config_db_postgres_config_proto = out.File
	file_config_db_postgres_config_proto_goTypes = nil
	file_config_db_postgres_config_proto_depIdxs = nil
}
