// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: config/queue/nats/config.proto

package nats

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
	meta "zengo/platform/api/config/meta"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NATS config document.
//
// Config is the typed NATS configuration loaded by the platform runtime.
type Config struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Config kind.
	//
	// kind is the logical config kind used by the loader.
	Kind string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	// Config API version.
	//
	// api_version identifies the document version used for compatibility over time.
	ApiVersion string `protobuf:"bytes,2,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	// NATS settings.
	//
	// spec contains the NATS connection settings consumed by the runtime.
	Spec          *Spec `protobuf:"bytes,3,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_config_queue_nats_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_config_queue_nats_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_config_queue_nats_config_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Config) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *Config) GetSpec() *Spec {
	if x != nil {
		return x.Spec
	}
	return nil
}

// NATS settings.
//
// Spec configures NATS connectivity and reconnect behavior.
type Spec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Server URLs.
	//
	// urls lists one or more NATS server URLs.
	Urls []string `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"`
	// Client name.
	//
	// name is the optional logical client name.
	Name *string `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	// Auth token.
	//
	// token is the optional token used for authentication.
	Token *string `protobuf:"bytes,3,opt,name=token,proto3,oneof" json:"token,omitempty"`
	// Username.
	//
	// username is the optional username used for authentication.
	Username *string `protobuf:"bytes,4,opt,name=username,proto3,oneof" json:"username,omitempty"`
	// Password.
	//
	// password is the optional password used for authentication.
	Password *string `protobuf:"bytes,5,opt,name=password,proto3,oneof" json:"password,omitempty"`
	// TLS settings.
	//
	// tls configures TLS and optional mTLS for the client connection.
	Tls *meta.ClientTLS `protobuf:"bytes,6,opt,name=tls,proto3" json:"tls,omitempty"`
	// Reconnect limit.
	//
	// max_reconnects bounds reconnect attempts before the client gives up.
	MaxReconnects *int32 `protobuf:"varint,7,opt,name=max_reconnects,json=maxReconnects,proto3,oneof" json:"max_reconnects,omitempty"`
	// Connect timeout.
	//
	// connect_timeout bounds initial connection attempts.
	ConnectTimeout *durationpb.Duration `protobuf:"bytes,8,opt,name=connect_timeout,json=connectTimeout,proto3,oneof" json:"connect_timeout,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Spec) Reset() {
	*x = Spec{}
	mi := &file_config_queue_nats_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Spec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Spec) ProtoMessage() {}

func (x *Spec) ProtoReflect() protoreflect.Message {
	mi := &file_config_queue_nats_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Spec.ProtoReflect.Descriptor instead.
func (*Spec) Descriptor() ([]byte, []int) {
	return file_config_queue_nats_config_proto_rawDescGZIP(), []int{1}
}

func (x *Spec) GetUrls() []string {
	if x != nil {
		return x.Urls
	}
	return nil
}

func (x *Spec) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *Spec) GetToken() string {
	if x != nil && x.Token != nil {
		return *x.Token
	}
	return ""
}

func (x *Spec) GetUsername() string {
	if x != nil && x.Username != nil {
		return *x.Username
	}
	return ""
}

func (x *Spec) GetPassword() string {
	if x != nil && x.Password != nil {
		return *x.Password
	}
	return ""
}

func (x *Spec) GetTls() *meta.ClientTLS {
	if x != nil {
		return x.Tls
	}
	return nil
}

func (x *Spec) GetMaxReconnects() int32 {
	if x != nil && x.MaxReconnects != nil {
		return *x.MaxReconnects
	}
	return 0
}

func (x *Spec) GetConnectTimeout() *durationpb.Duration {
	if x != nil {
		return x.ConnectTimeout
	}
	return nil
}

var File_config_queue_nats_config_proto protoreflect.FileDescriptor

const file_config_queue_nats_config_proto_rawDesc = "" +
	"\n" +
	"\x1econfig/queue/nats/config.proto\x12\x11zengo.config.nats\x1a\x15config/meta/tls.proto\x1a\x1egoogle/protobuf/duration.proto\"j\n" +
	"\x06Config\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x1f\n" +
	"\vapi_version\x18\x02 \x01(\tR\n" +
	"apiVersion\x12+\n" +
	"\x04spec\x18\x03 \x01(\v2\x17.zengo.config.nats.SpecR\x04spec\"\x89\x03\n" +
	"\x04Spec\x12\x12\n" +
	"\x04urls\x18\x01 \x03(\tR\x04urls\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x19\n" +
	"\x05token\x18\x03 \x01(\tH\x01R\x05token\x88\x01\x01\x12\x1f\n" +
	"\busername\x18\x04 \x01(\tH\x02R\busername\x88\x01\x01\x12\x1f\n" +
	"\bpassword\x18\x05 \x01(\tH\x03R\bpassword\x88\x01\x01\x12.\n" +
	"\x03tls\x18\x06 \x01(\v2\x1c.zengo.config.meta.ClientTLSR\x03tls\x12*\n" +
	"\x0emax_reconnects\x18\a \x01(\x05H\x04R\rmaxReconnects\x88\x01\x01\x12G\n" +
	"\x0fconnect_timeout\x18\b \x01(\v2\x19.google.protobuf.DurationH\x05R\x0econnectTimeout\x88\x01\x01B\a\n" +
	"\x05_nameB\b\n" +
	"\x06_tokenB\v\n" +
	"\t_usernameB\v\n" +
	"\t_passwordB\x11\n" +
	"\x0f_max_reconnectsB\x12\n" +
	"\x10_connect_timeoutB&Z$zengo/platform/api/config/queue/natsb\x06proto3"

var (
	file_config_queue_nats_config_proto_rawDescOnce sync.Once
	file_config_queue_nats_config_proto_rawDescData []byte
)

func file_config_queue_nats_config_proto_rawDescGZIP() []byte {
	file_config_queue_nats_config_proto_rawDescOnce.Do(func() {
		file_config_queue_nats_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_config_queue_nats_config_proto_rawDesc), len(file_config_queue_nats_config_proto_rawDesc)))
	})
	return file_config_queue_nats_config_proto_rawDescData
}

var file_config_queue_nats_config_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_config_queue_nats_config_proto_goTypes = []any{
	(*Config)(nil),              // 0: zengo.config.nats.Config
	(*Spec)(nil),                // 1: zengo.config.nats.Spec
	(*meta.ClientTLS)(nil),      // 2: zengo.config.meta.ClientTLS
	(*durationpb.Duration)(nil), // 3: google.protobuf.Duration
}
var file_config_queue_nats_config_proto_depIdxs = []int32{
	1, // 0: zengo.config.nats.Config.spec:type_name -> zengo.config.nats.Spec
	2, // 1: zengo.config.nats.Spec.tls:type_name -> zengo.config.meta.ClientTLS
	3, // 2: zengo.config.nats.Spec.connect_timeout:type_name -> google.protobuf.Duration
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_config_queue_nats_config_proto_init() }
func file_config_queue_nats_config_proto_init() {
	if File_config_queue_nats_config_proto != nil {
		return
	}
	file_config_queue_nats_config_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_config_queue_nats_config_proto_rawDesc), len(file_config_queue_nats_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_config_queue_nats_config_proto_goTypes,
		DependencyIndexes: file_config_queue_nats_config_proto_depIdxs,
		MessageInfos:      file_config_queue_nats_config_proto_msgTypes,
	}.Build()
	File_config_queue_nats_config_proto = out.File
	file_config_queue_nats_config_proto_goTypes = nil
	file_config_queue_nats_config_proto_depIdxs = nil
}
