package generator

import (
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"zengo/platform/internal/manifest"
)

const generatedPostgresMigrationHeader = "-- Code generated by zengo gen. DO NOT EDIT."

// PostgresMigrationPathAt returns the managed baseline migration path for root.
func PostgresMigrationPathAt(root string) string {
	return filepath.Join(root, "migrations", "001_init.sql")
}

// GeneratePostgresMigrationAt renders the managed baseline Postgres migration
// from generated proto schema metadata when the service enables Postgres.
func GeneratePostgresMigrationAt(root string, m *manifest.Manifest) error {
	if m == nil || m.DB == nil || m.DB.Postgres == nil {
		return nil
	}
	manifestData, err := ReadRepositorySchemaAt(root)
	if err != nil {
		return fmt.Errorf("read repository schema: %w", err)
	}
	if len(manifestData.Repositories) == 0 {
		return nil
	}
	path := PostgresMigrationPathAt(root)
	exists, managed, err := postgresMigrationState(path)
	if err != nil {
		return err
	}
	if exists && !managed {
		return nil
	}
	body := renderPostgresMigration(manifestData.Repositories)
	err = os.MkdirAll(filepath.Dir(path), 0o755)
	if err != nil {
		return err
	}
	return os.WriteFile(path, []byte(body), 0o644)
}

// ShouldTrackPostgresMigrationAt reports whether freshness checks should manage
// the baseline migration for root.
func ShouldTrackPostgresMigrationAt(root string, m *manifest.Manifest) (bool, error) {
	if m == nil || m.DB == nil || m.DB.Postgres == nil {
		return false, nil
	}
	path := PostgresMigrationPathAt(root)
	exists, managed, err := postgresMigrationState(path)
	if err != nil {
		return false, err
	}
	if exists {
		return managed, nil
	}
	return HasRepositorySchemasAt(root)
}

func postgresMigrationState(path string) (bool, bool, error) {
	data, err := os.ReadFile(path)
	if os.IsNotExist(err) {
		return false, true, nil
	}
	if err != nil {
		return false, false, err
	}
	return true, strings.HasPrefix(string(data), generatedPostgresMigrationHeader), nil
}

func renderPostgresMigration(repositories []RepositorySchema) string {
	sorted := append([]RepositorySchema(nil), repositories...)
	slices.SortFunc(sorted, func(left, right RepositorySchema) int {
		return strings.Compare(left.Table, right.Table)
	})
	var b strings.Builder

	b.WriteString(generatedPostgresMigrationHeader)
	b.WriteString("\n\n")
	for index, repository := range sorted {
		if index > 0 {
			b.WriteString("\n")
		}
		fmt.Fprintf(&b, "CREATE TABLE IF NOT EXISTS %s (\n", repository.Table)
		for columnIndex, column := range repository.Columns {
			b.WriteString("    ")
			b.WriteString(renderPostgresColumn(column))
			if columnIndex < len(repository.Columns)-1 {
				b.WriteString(",")
			}
			b.WriteString("\n")
		}
		b.WriteString(");\n")
	}
	return b.String()
}

func renderPostgresColumn(column RepositoryColumn) string {
	parts := []string{column.Name, column.SQLType}
	if column.PrimaryKey {
		parts = append(parts, "PRIMARY KEY")
	} else {
		if !column.Nullable {
			parts = append(parts, "NOT NULL")
		}
		if column.Unique {
			parts = append(parts, "UNIQUE")
		}
	}
	if column.DefaultSQL != "" {
		parts = append(parts, "DEFAULT", column.DefaultSQL)
	}
	return strings.Join(parts, " ")
}
