package main

import (
	"fmt"
	"strings"
	"zengo/platform/api/zengo/options"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/pluginpb"
)

// main runs the custom protoc plugin that generates grpc-gateway and runtime helpers.
func main() {
	protogen.Options{}.Run(runPlugin)
}

func runPlugin(gen *protogen.Plugin) error {
	gen.SupportedFeatures = uint64(pluginpb.CodeGeneratorResponse_FEATURE_PROTO3_OPTIONAL)
	for _, file := range gen.Files {
		if !file.Generate {
			continue
		}
		err := generateFile(gen, file)
		if err != nil {
			return err
		}
	}
	return generateSchemaMetadata(gen)
}

// generateFile emits one zengo helper file for each generated proto version package.
func generateFile(gen *protogen.Plugin, file *protogen.File) error {
	if len(file.Services) == 0 || isOptionsFile(file) {
		return nil
	}

	version := versionFromPackage(string(file.Desc.Package()))
	filename := fmt.Sprintf("zengo/register_%s.pb.go", version)
	g := gen.NewGeneratedFile(filename, genImportPath(file))
	g.P("// Code generated by protoc-gen-zengo. DO NOT EDIT.")
	g.P("package zengo")

	n := analyzeNeeds(file, version)
	g.P()
	writeImports(g, file, n)

	for _, svc := range file.Services {
		if isEventService(svc) {
			if isHubVersion(version) {
				writeKafkaConsumer(g, svc, version)
			}
			continue
		}
		writeGRPCRegister(g, file, svc, version)
		writeGatewayRegister(g, file, svc, version)
		if isHubVersion(version) {
			writeKafkaProduce(g, svc)
		}
	}
	return nil
}

type needs struct {
	context bool
	fmt     bool
	gateway bool
	grpc    bool
	kafka   bool
	policy  bool
	router  bool
}

func analyzeNeeds(file *protogen.File, version string) needs {
	var n needs
	for _, svc := range file.Services {
		if isEventService(svc) {
			if isHubVersion(version) {
				n.context = true
				n.kafka = true
				n.policy = true
				n.router = true
			}
			continue
		}
		n.context = true
		n.gateway = true
		n.grpc = true
		for _, method := range svc.Methods {
			if isHubVersion(version) && kafkaProduce(method) != nil {
				n.context = true
				n.fmt = true
				n.kafka = true
			}
		}
	}
	return n
}

func writeImports(g *protogen.GeneratedFile, file *protogen.File, n needs) {
	g.P("import (")
	if n.context {
		g.P(`	"context"`)
	}
	if n.fmt {
		g.P(`	"fmt"`)
	}
	if n.gateway || n.grpc {
		g.P()
	}
	if n.gateway {
		g.P(`	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"`)
	}
	if n.grpc {
		g.P(`	"google.golang.org/grpc"`)
	}
	if n.gateway || n.grpc {
		g.P()
		g.Import(file.GoImportPath)
	}
	if n.kafka {
		g.P(`	"zengo/platform/sdk/transport/queue/kafka"`)
	}
	if n.policy {
		g.P(`	"zengo/platform/sdk/policy"`)
	}
	if n.router {
		g.P(`	"zengo/platform/sdk/router"`)
	}
	g.P(")")
	g.P()
}

func genImportPath(file *protogen.File) protogen.GoImportPath {
	base := string(file.GoImportPath)
	idx := strings.Index(base, "/gen/")
	if idx >= 0 {
		base = base[:idx]
	}
	return protogen.GoImportPath(base + "/gen/zengo")
}

func writeGRPCRegister(g *protogen.GeneratedFile, file *protogen.File, svc *protogen.Service, version string) {
	fn := registerName(svc, version)
	serverIdent := protogen.GoIdent{GoImportPath: file.GoImportPath, GoName: svc.GoName + "Server"}
	registerIdent := protogen.GoIdent{GoImportPath: file.GoImportPath, GoName: "Register" + svc.GoName + "Server"}
	g.P("func ", fn, "(server *grpc.Server, handler ", g.QualifiedGoIdent(serverIdent), ") {")
	g.P("	", g.QualifiedGoIdent(registerIdent), "(server, handler)")
	g.P("}")
	g.P()
}

func writeGatewayRegister(g *protogen.GeneratedFile, file *protogen.File, svc *protogen.Service, version string) {
	fn := gatewayName(svc, version)
	registerIdent := protogen.GoIdent{
		GoImportPath: file.GoImportPath,
		GoName:       "Register" + svc.GoName + "HandlerFromEndpoint",
	}
	g.P("func ", fn, "() func(context.Context, *runtime.ServeMux, string, []grpc.DialOption) error {")
	g.P("	return ", g.QualifiedGoIdent(registerIdent))
	g.P("}")
	g.P()
}

func writeKafkaProduce(g *protogen.GeneratedFile, svc *protogen.Service) {
	for _, method := range svc.Methods {
		produce := kafkaProduce(method)
		if produce != nil {
			g.P(
				"func Publish",
				method.GoName,
				"(ctx context.Context, producer *kafka.Producer, brokers []string, apiVersion string, payload []byte) error {",
			)
			g.P("	if producer == nil {")
			g.P(`		return fmt.Errorf("kafka producer is nil")`)
			g.P("	}")
			g.P(
				`	return producer.Publish(ctx, brokers, "`,
				produce.GetTopic(),
				`", apiVersion, "`,
				produce.GetEvent(),
				`", payload)`,
			)
			g.P("}")
			g.P()
		}
	}
}

func writeKafkaConsumer(g *protogen.GeneratedFile, svc *protogen.Service, version string) {
	for _, method := range svc.Methods {
		consume := kafkaConsume(method)
		if consume != nil {
			handlerName := kafkaHandlerName(svc, method, version)
			g.P(
				"func Register",
				handlerName,
				"(consumer *kafka.Consumer, brokers []string, policyOpts policy.Options, handler func(context.Context, router.EventEnvelope) error) error {",
			)
			g.P("	return consumer.Register(kafka.ConsumeSpec{")
			g.P(`		Topic:   "`, consume.GetTopic(), `",`)
			g.P(`		Group:   "`, consume.GetGroup(), `",`)
			g.P("		Brokers: brokers,")
			g.P("		Policy:  policyOpts,")
			g.P("		Handler: handler,")
			g.P("	})")
			g.P("}")
			g.P()
		}
	}
}

func registerName(svc *protogen.Service, version string) string {
	return "RegisterGRPC" + strings.TrimSuffix(svc.GoName, "Service") + strings.ToUpper(version[:1]) + version[1:]
}

func gatewayName(svc *protogen.Service, version string) string {
	return "GatewayRegister" + strings.TrimSuffix(svc.GoName, "Service") + strings.ToUpper(version[:1]) + version[1:]
}

func kafkaHandlerName(svc *protogen.Service, method *protogen.Method, version string) string {
	return svc.GoName + method.GoName + strings.ToUpper(version[:1]) + version[1:]
}

func isHubVersion(version string) bool {
	return version == "hub"
}

func versionFromPackage(pkg string) string {
	if strings.HasSuffix(pkg, ".hub") {
		return "hub"
	}
	idx := strings.LastIndex(pkg, ".")
	if idx < 0 {
		return "v0"
	}
	v := pkg[idx+1:]
	if strings.HasPrefix(v, "v") {
		return v
	}
	return "v0"
}

func isOptionsFile(file *protogen.File) bool {
	return strings.HasPrefix(string(file.Desc.Package()), "zengo.options")
}

func isEventService(svc *protogen.Service) bool {
	return strings.HasSuffix(svc.GoName, "EventHandler")
}

func kafkaProduce(method *protogen.Method) *options.KafkaProduce {
	hasExtension := proto.HasExtension(method.Desc.Options(), options.E_Produce)
	if !hasExtension {
		return nil
	}
	extension := proto.GetExtension(method.Desc.Options(), options.E_Produce)
	produce, ok := extension.(*options.KafkaProduce)
	if !ok || produce == nil || produce.Topic == "" {
		return nil
	}
	return produce
}

func kafkaConsume(method *protogen.Method) *options.KafkaConsume {
	hasExtension := proto.HasExtension(method.Desc.Options(), options.E_Consume)
	if !hasExtension {
		return nil
	}
	extension := proto.GetExtension(method.Desc.Options(), options.E_Consume)
	consume, ok := extension.(*options.KafkaConsume)
	if !ok || consume == nil || consume.Topic == "" {
		return nil
	}
	return consume
}
