syntax = "proto3";

package notification.hub;

option go_package = "github.com/zengo/notification-service/gen/api/hub/notification;notificationhub";

import "google/api/annotations.proto";
import "google/protobuf/empty.proto";
import "zengo/options/kafka.proto";

service NotificationService {
  rpc GetStatus(google.protobuf.Empty) returns (GetStatusResponse) {
    option (google.api.http) = {get: "/status"};
  }
}

service NotificationEventHandler {
  rpc OnUserCreated(UserCreatedEvent) returns (google.protobuf.Empty) {
    option (zengo.options.consume) = {topic: "user.events", group: "notification-service"};
  }
}

message User {
  string id = 1;
  string email = 2;
  string name = 3;
  string display_name = 4;
}

message UserCreatedEvent {
  string api_version = 1;
  User user = 2;
}

message GetStatusResponse {
  string service = 1;
  string state = 2;
}
