package cqlgen

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"text/template"
	"zengo/platform/internal/codegen"
)

// Query is one named CQL query extracted from a .cql file.
type Query struct {
	// Name is the generated Go constant prefix for the query.
	Name string
	// Query is the raw CQL statement body without the leading "-- name" line.
	Query string
}

// Generate parses .cql files under configPath/cql and writes a Go constants file to outDir.
func Generate(configPath, outDir string) error {
	queries, err := parseCQL(filepath.Join(configPath, "cql"))
	if err != nil {
		return err
	}
	err = os.MkdirAll(outDir, 0o755)
	if err != nil {
		return err
	}
	outPath := filepath.Join(outDir, "queries_gen.go")
	var buf bytes.Buffer
	err = cqlTemplate.Execute(&buf, queries)
	if err != nil {
		return err
	}
	var src []byte

	src, err = codegen.FormatSource(buf.Bytes(), outPath)
	if err != nil {
		return err
	}
	return os.WriteFile(outPath, src, 0o644)
}

func parseCQL(dir string) ([]Query, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, err
	}
	var queries []Query
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".cql") {
			continue
		}
		if entry.Name() == "schema.cql" {
			continue
		}
		data, err := os.ReadFile(filepath.Join(dir, entry.Name()))
		if err != nil {
			return nil, err
		}
		for block := range strings.SplitSeq(string(data), ";") {
			block = strings.TrimSpace(block)
			if block == "" {
				continue
			}
			lines := strings.Split(block, "\n")
			if len(lines) == 0 || !strings.HasPrefix(lines[0], "-- name:") {
				continue
			}
			name := strings.TrimSpace(strings.TrimPrefix(lines[0], "-- name:"))
			query := strings.TrimSpace(strings.Join(lines[1:], "\n"))
			queries = append(queries, Query{Name: strings.Split(name, " ")[0], Query: query})
		}
	}
	return queries, nil
}

var cqlTemplate = template.Must(template.New("cql").Parse(`// Code generated by zengo cqlgen. DO NOT EDIT.
package cqlgen

const (
{{- range . }}
	{{ .Name }}Query = ` + "`{{ .Query }}`" + `
{{- end }}
)
`))
